const TOKEN=document.querySelector('meta[name="rrg-token"]').content;
const app=document.getElementById('app');
let DATA=null;
let VIEW='dashboard';
let selectedRun='';
let selectedQuestion=1;

const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const qs=(obj={})=>new URLSearchParams(Object.entries(obj).filter(([,value])=>value!==undefined&&value!==null&&value!=='')).toString();
async function api(path,params){const response=await fetch(path+(params?'?'+qs(params):''),{headers:{'X-RRG-Token':TOKEN}});const data=await response.json();if(!response.ok||data.error)throw new Error(data.error||`HTTP ${response.status}`);return data}
async function post(path,payload){const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-RRG-Token':TOKEN},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok||data.error)throw new Error(data.error||`HTTP ${response.status}`);return data}
function toast(message,bad=false){const node=document.getElementById('toast');node.textContent=message;node.className='show'+(bad?' bad':'');setTimeout(()=>node.className='',2600)}
function stageIndex(id){const index=DATA.stages.findIndex(stage=>stage.id===id);return Math.max(0,index)%6}
function stageChip(id){return `<span class="stage stage-${stageIndex(id)}">${esc(id)}</span>`}
function pill(value,label=value?'yes':'no'){return `<span class="pill ${value?'ok':''}">${esc(label)}</span>`}
function banner(type,text){return `<div class="banner ${type}">${esc(text)}</div>`}
function loading(text='Loading…'){app.innerHTML=`<div class="card loading">${esc(text)}</div>`}
function value(id){return document.getElementById(id)?.value??''}
function checked(id){return !!document.getElementById(id)?.checked}
function lines(text){return String(text||'').split('\n').map(item=>item.trim()).filter(Boolean)}
async function busy(button,label,work){const prior=button.textContent;button.disabled=true;button.textContent=label;try{return await work()}finally{button.disabled=false;button.textContent=prior}}

function applyData(data){DATA=data;document.getElementById('project-name').textContent=DATA.project;document.getElementById('project-root').textContent=DATA.root}
async function refresh(){applyData(await api('/api/bootstrap'));render()}
function render(){({dashboard:renderDashboard,setup:renderSetup,convert:renderConvert,build:renderBuild,prompts:renderPrompts,runs:renderRuns,review:renderReview,origin:renderOrigin,projects:renderProjects}[VIEW]||renderDashboard)()}
function activateView(view){VIEW=view;document.querySelectorAll('nav button').forEach(item=>item.classList.toggle('active',item.dataset.view===view));render()}
document.querySelectorAll('nav button').forEach(button=>button.addEventListener('click',()=>activateView(button.dataset.view)));

function renderProjects(){
  const workspace=DATA.workspace||{enabled:false,projects:[]};
  if(!workspace.enabled){app.innerHTML=`<div class="card hero"><div><div class="eyebrow">Project isolation</div><h2>Projects</h2><p>This GUI is locked to one project. Restart with <code>rrg gui --workspace /path/to/workspace</code> to enable safe project switching and creation.</p></div></div><div class="card">${banner('ok',`Active project: ${DATA.project}`)}<p><code>${esc(DATA.root)}</code></p></div>`;return}
  const rows=workspace.projects.map(project=>`<tr><td><b>${esc(project.name)}</b>${project.error?`<div class="mut">${esc(project.error)}</div>`:''}</td><td><code>${esc(project.root)}</code></td><td>${project.active?pill(true,'active'):(project.valid?pill(false,'ready'):pill(false,'invalid'))}</td><td>${project.active?'':`<button class="btn" data-project-root="${esc(project.root)}" ${project.valid?'':'disabled'}>Open</button>`}</td></tr>`).join('');
  app.innerHTML=`<div class="card hero"><div><div class="eyebrow">Confined workspace</div><h2>Projects</h2><p>Each study keeps separate data, manifests, packages, runs, and withheld results. Switching reloads the full project-scoped interface.</p></div><div class="pill">${esc(workspace.root)}</div></div><div class="card"><h2>Workspace projects</h2><table><thead><tr><th>Project</th><th>Relative root</th><th>Status</th><th></th></tr></thead><tbody>${rows}</tbody></table></div><div class="card"><h2>New project</h2><p class="mut">Create a new child directory inside this workspace from the standard RRG scaffold.</p><div class="row"><div class="field"><label>Project name</label><input id="new-project-name" type="text" placeholder="MovieRatings demo"></div><div class="field"><label>Workspace-relative directory</label><input id="new-project-path" type="text" placeholder="demo_projects/MovieRatings"></div></div><div class="actions"><button class="btn primary" id="new-project-create">Create project</button></div><div id="new-project-result"></div></div>`;
  document.querySelectorAll('[data-project-root]').forEach(button=>button.onclick=event=>busy(event.currentTarget,'Opening…',async()=>{applyData(await post('/api/project/select',{root:button.dataset.projectRoot}));selectedRun='';selectedQuestion=1;activateView('dashboard');toast(`Opened ${DATA.project}`)}).catch(error=>toast(error.message,true)));
  document.getElementById('new-project-create').onclick=event=>busy(event.currentTarget,'Creating…',async()=>{applyData(await post('/api/project/create',{name:value('new-project-name'),path:value('new-project-path')}));selectedRun='';selectedQuestion=1;activateView('setup');toast(`Created ${DATA.project}`)}).catch(error=>{toast(error.message,true);document.getElementById('new-project-result').innerHTML=banner('bad',error.message)});
}

function renderDashboard(){
  const packages=DATA.stages.reduce((sum,stage)=>sum+stage.packages,0);
  const returned=DATA.stages.reduce((sum,stage)=>sum+stage.returned,0);
  const issues=DATA.preflight.checks.filter(check=>check.severity==='error').length;
  const rows=DATA.stages.map(stage=>`<tr><td>${stageChip(stage.id)}</td><td>${stage.enabled?pill(true,'enabled'):pill(false,'disabled')}</td><td>${esc(stage.opens||'—')}</td><td>${esc(stage.models.map(item=>item.model).join(', ')||'—')}</td><td>${stage.packages}</td><td>${stage.returned}</td><td>${stage.graded}</td></tr>`).join('');
  const checks=DATA.preflight.checks.filter(check=>check.severity!=='ok').map(check=>`<li><span class="pill ${check.severity==='error'?'bad':'warn'}">${esc(check.severity)}</span> ${esc(check.name)} — ${esc(check.detail)}</li>`).join('');
  app.innerHTML=`<div class="card hero"><div><div class="eyebrow">Degrees-of-freedom validation</div><h2>${esc(DATA.project)}</h2><p>One engine for project setup, verified data conversion, blinded package assembly, staged prompts, returned-run review, comparison, and human scorecards.</p></div><button class="btn" id="dash-refresh">Refresh</button></div>
  <div class="grid"><div class="metric"><div class="value">${packages}</div><div class="label">Published packages</div></div><div class="metric"><div class="value">${returned}</div><div class="label">Returned runs</div></div><div class="metric"><div class="value">${issues}</div><div class="label">Blocking preflight issues</div></div></div>
  <div class="card"><h2>Stage status</h2><table><thead><tr><th>Stage</th><th>Status</th><th>Opens</th><th>Models</th><th>Packaged</th><th>Returned</th><th>Graded</th></tr></thead><tbody>${rows}</tbody></table></div>
  <div class="card"><h2>Preflight</h2>${DATA.preflight.ok?banner('ok','All enabled stages and referenced inputs pass preflight.'):banner('bad','The project is not ready; resolve the checks below.')} ${checks?`<ul>${checks}</ul>`:'<p class="mut">No warnings or errors.</p>'}</div>`;
  document.getElementById('dash-refresh').onclick=()=>{loading('Refreshing project…');refresh().catch(error=>{toast(error.message,true);render()})};
}

function renderSetup(){
  const study=DATA.study||{},dataset=study.dataset||{},aux=dataset.aux||{},solution=study.given_solution||{},questions=study.questions||{},held=study.held_constants||{},original=study.original||{},delivery=study.deliverable||{},guide=delivery.method_guide||{};
  const additional=(study.additional||[]).map(item=>[item.name||'',item.file||'',item.note||''].join(' :: ')).join('\n');
  const stageRows=DATA.stages.map((stage,index)=>`<tr><td>${stageChip(stage.id)}</td><td><input type="checkbox" id="stage-enabled-${index}" ${stage.enabled?'checked':''}></td><td><input type="text" id="stage-prompt-${index}" value="${esc(stage.prompt)}"></td><td><textarea id="stage-send-${index}">${esc((stage.send||[]).join('\n'))}</textarea></td><td><input type="text" id="stage-block-${index}" value="${esc(stage.blocked_reason)}"></td></tr>`).join('');
  app.innerHTML=`<div class="card hero"><div><div class="eyebrow">Project cartridge</div><h2>Setup</h2><p>Edit known engine and study fields. Unknown YAML fields are preserved when this form saves.</p></div><div class="pill">${esc(DATA.config_path)} · ${esc(DATA.study_path)}</div></div>
  <div class="card"><h2>Study identity and inputs</h2><div class="row"><div class="field"><label>Project name</label><input id="setup-project" type="text" value="${esc(DATA.project)}"></div><div class="field"><label>Study title</label><input id="setup-title" type="text" value="${esc(study.title||'')}"></div><div class="field"><label>Overview file</label><input id="setup-overview" type="text" value="${esc(study.overview_file||'')}"></div></div>
  <h3>Dataset</h3><div class="row"><div class="field"><label>Authoritative source</label><input id="setup-source" type="text" value="${esc(dataset.source||'')}"></div><div class="field"><label>Analysis-copy stem</label><input id="setup-main" type="text" value="${esc(dataset.main_name||'')}"></div><div class="field"><label>Merge key</label><input id="setup-key" type="text" value="${esc(dataset.merge_key||'')}"></div></div><div class="row"><div class="field"><label>Formats (comma separated)</label><input id="setup-formats" type="text" value="${esc((dataset.formats||[]).join(', '))}"></div><div class="field"><label>Codebook</label><input id="setup-codebook" type="text" value="${esc(dataset.codebook||'')}"></div><div class="field"><label>Metadata sidecar</label><input id="setup-metadata" type="text" value="${esc(dataset.metadata||'')}"></div></div><label>Data-orientation prompt text</label><textarea id="setup-orientation">${esc(dataset.orientation||'')}</textarea>
  <div class="row"><label class="check"><input id="setup-aux-enabled" type="checkbox" ${aux.enabled?'checked':''}> Auxiliary dataset enabled</label><div class="field"><label>Aux name</label><input id="setup-aux-name" type="text" value="${esc(aux.name||'')}"></div><div class="field"><label>Aux file</label><input id="setup-aux-file" type="text" value="${esc(aux.file||'')}"></div><div class="field"><label>Aux note</label><input id="setup-aux-note" type="text" value="${esc(aux.note||'')}"></div></div>
  <h3>Questions and held constants</h3><div class="row"><div class="field"><label>Questions file</label><input id="setup-questions" type="text" value="${esc(questions.file||'')}"></div><div class="field"><label>Question count</label><input id="setup-count" type="number" min="1" value="${esc(questions.count||'')}"></div><div class="field"><label>Question map</label><input id="setup-map" type="text" value="${esc(questions.map||'')}"></div></div><div class="row"><div class="field"><label>Held-constants file</label><input id="setup-held-file" type="text" value="${esc(held.file||'')}"></div><div class="field"><label>Summary</label><input id="setup-held-summary" type="text" value="${esc(held.summary||'')}"></div><div class="field"><label>QA groups</label><input id="setup-held-groups" type="text" value="${esc(held.qa_groups||'')}"></div></div>
  <h3>Original work and supplied solution</h3><div class="row"><div class="field"><label>Original methodology</label><input id="setup-method" type="text" value="${esc(original.methodology_file||'')}"></div><div class="field"><label>Withheld results key</label><input id="setup-keydir" type="text" value="${esc(original.results_key||'')}"></div><div class="field"><label>Origin model</label><input id="setup-origin-model" type="text" value="${esc(original.model||'')}"></div><div class="field"><label>Origin vendor</label><input id="setup-origin-vendor" type="text" value="${esc(original.vendor||'')}"></div></div><label class="check"><input id="setup-solution-enabled" type="checkbox" ${solution.enabled?'checked':''}> Fixed/supplied solution enabled</label><div class="row"><div class="field"><label>Solution glossary</label><input id="setup-solution-glossary" type="text" value="${esc(solution.glossary||'')}"></div><div class="field"><label>Solution artifacts (one per line)</label><textarea id="setup-solution-artifacts">${esc((solution.artifacts||[]).join('\n'))}</textarea></div><div class="field"><label>Solution instruction</label><textarea id="setup-solution-note">${esc(solution.note||'')}</textarea></div></div><label>Additional inputs: name :: file :: note</label><textarea id="setup-additional">${esc(additional)}</textarea>
  <h3>Deliverable</h3><div class="row"><div class="field"><label>Report filename template</label><input id="setup-report" type="text" value="${esc(delivery.report_name||'')}"></div><label class="check"><input id="setup-guide-enabled" type="checkbox" ${guide.enabled?'checked':''}> Method guide enabled</label><div class="field"><label>Guide name</label><input id="setup-guide-name" type="text" value="${esc(guide.name||'')}"></div><div class="field"><label>Guide file</label><input id="setup-guide-file" type="text" value="${esc(guide.file||'')}"></div></div><label>Reporting specification</label><textarea id="setup-reporting">${esc(delivery.reporting_spec||'')}</textarea></div>
  <div class="card"><h2>Stages</h2><table><thead><tr><th>Stage</th><th>Enabled</th><th>Prompt</th><th>Send tokens/paths</th><th>Blocked reason</th></tr></thead><tbody>${stageRows}</tbody></table></div>
  <div class="card"><h2>Models per stage</h2><p class="mut">Set which models run at each stage. The dispatch slug is substituted into the start command (<code>{model_slug}</code>); leave it blank to skip.</p><div id="roster-editor">${rosterEditorHTML()}</div><label>Dispatch start template</label><input id="setup-dispatch" type="text" value="${esc(DATA.dispatch_start||'')}"><div class="actions"><button class="btn primary" id="setup-save">Save and preflight</button><button class="btn" id="setup-check">Run preflight</button></div><div id="setup-result"></div></div>`;
  wireRosterEditor();
  document.getElementById('setup-save').onclick=event=>busy(event.currentTarget,'Saving…',saveSetup).catch(error=>toast(error.message,true));
  document.getElementById('setup-check').onclick=event=>busy(event.currentTarget,'Checking…',async()=>{const result=await api('/api/preflight');document.getElementById('setup-result').innerHTML=preflightHTML(result)}).catch(error=>toast(error.message,true));
}

function modelRowHTML(stageId,model={},slug=''){return `<div class="rost-row" data-stage="${esc(stageId)}"><input class="rost-model" placeholder="model" value="${esc(model.model||'')}"><input class="rost-vendor" placeholder="vendor" value="${esc(model.vendor||'')}"><input class="rost-type" placeholder="type (open/frontier)" value="${esc(model.type||'')}"><input class="rost-license" placeholder="license" value="${esc(model.license||'')}"><input class="rost-slug" placeholder="dispatch slug" value="${esc(slug)}"><button type="button" class="btn danger rost-del" title="Remove model">×</button></div>`}
function rosterEditorHTML(){const slugs=DATA.dispatch_slugs||{};const labels='<div class="rost-labels"><span>Model</span><span>Vendor</span><span>Type</span><span>License</span><span>Dispatch slug</span><span></span></div>';return DATA.stages.map(stage=>{const models=stage.models||[];const rows=models.map(model=>modelRowHTML(stage.id,model,slugs[model.model]||'')).join('');return `<div class="rost-stage" data-stage="${esc(stage.id)}"><div class="rost-head">${stageChip(stage.id)}<button type="button" class="btn rost-add" data-stage="${esc(stage.id)}">+ Add model</button></div>${models.length?labels:''}<div class="rost-rows">${rows||'<div class="empty">No models configured for this stage.</div>'}</div></div>`}).join('')}
const ROST_LABELS='<div class="rost-labels"><span>Model</span><span>Vendor</span><span>Type</span><span>License</span><span>Dispatch slug</span><span></span></div>';
function wireRosterEditor(){const editor=document.getElementById('roster-editor');if(!editor)return;editor.querySelectorAll('.rost-add').forEach(button=>button.onclick=()=>{const stageEl=button.closest('.rost-stage');const rows=stageEl.querySelector('.rost-rows');const empty=rows.querySelector('.empty');if(empty)empty.remove();if(!stageEl.querySelector('.rost-labels'))rows.insertAdjacentHTML('beforebegin',ROST_LABELS);rows.insertAdjacentHTML('beforeend',modelRowHTML(button.dataset.stage));bindRosterDeletes(editor)});bindRosterDeletes(editor)}
function bindRosterDeletes(editor){editor.querySelectorAll('.rost-del').forEach(button=>button.onclick=()=>{const rows=button.closest('.rost-rows');button.closest('.rost-row').remove();if(!rows.querySelector('.rost-row'))rows.innerHTML='<div class="empty">No models configured for this stage.</div>'})}
function collectRoster(){const roster={},slugs={};DATA.stages.forEach(stage=>{roster[stage.id]=[]});document.querySelectorAll('#roster-editor .rost-row').forEach(row=>{const model=row.querySelector('.rost-model').value.trim();if(!model)return;roster[row.dataset.stage].push({model,vendor:row.querySelector('.rost-vendor').value.trim(),type:row.querySelector('.rost-type').value.trim(),license:row.querySelector('.rost-license').value.trim()});const slug=row.querySelector('.rost-slug').value.trim();if(slug)slugs[model]=slug});return {roster,slugs}}
async function saveSetup(){
  const {roster,slugs}=collectRoster();
  const additional=lines(value('setup-additional')).map(line=>{const [name='',file='',note='']=line.split('::').map(item=>item.trim());return {name,file,note}});
  const stagePatches=DATA.stages.map((stage,index)=>({id:stage.id,enabled:checked(`stage-enabled-${index}`),prompt:value(`stage-prompt-${index}`),send:lines(value(`stage-send-${index}`)),blocked_reason:value(`stage-block-${index}`)}));
  const payload={study:{title:value('setup-title'),overview_file:value('setup-overview'),dataset:{source:value('setup-source'),main_name:value('setup-main'),merge_key:value('setup-key'),formats:value('setup-formats').split(',').map(item=>item.trim()).filter(Boolean),codebook:value('setup-codebook'),metadata:value('setup-metadata'),orientation:value('setup-orientation'),aux:{enabled:checked('setup-aux-enabled'),name:value('setup-aux-name'),file:value('setup-aux-file'),note:value('setup-aux-note')}},given_solution:{enabled:checked('setup-solution-enabled'),glossary:value('setup-solution-glossary'),artifacts:lines(value('setup-solution-artifacts')),note:value('setup-solution-note')},additional,questions:{file:value('setup-questions'),count:Number(value('setup-count')),map:value('setup-map')},held_constants:{file:value('setup-held-file'),summary:value('setup-held-summary'),qa_groups:value('setup-held-groups')},original:{methodology_file:value('setup-method'),results_key:value('setup-keydir'),model:value('setup-origin-model'),vendor:value('setup-origin-vendor')},deliverable:{report_name:value('setup-report'),reporting_spec:value('setup-reporting'),method_guide:{enabled:checked('setup-guide-enabled'),name:value('setup-guide-name'),file:value('setup-guide-file')}}},engine:{project_name:value('setup-project'),stages:stagePatches,roster,model_slugs:slugs,dispatch_start:value('setup-dispatch')}};
  DATA=await post('/api/setup',payload);document.getElementById('project-name').textContent=DATA.project;document.getElementById('project-root').textContent=DATA.root;toast('Project configuration saved');renderSetup();
}
function preflightHTML(result){const rows=result.checks.map(check=>`<tr><td>${check.severity==='ok'?pill(true,'✓'):`<span class="pill ${check.severity==='error'?'bad':'warn'}">${esc(check.severity)}</span>`}</td><td>${esc(check.name)}</td><td>${esc(check.detail)}</td></tr>`).join('');return `${result.ok?banner('ok','Preflight passed.'):banner('bad','Preflight found blocking issues.')}<table><tbody>${rows}</tbody></table>`}

function renderConvert(){const dataset=DATA.dataset||{};app.innerHTML=`<div class="card hero"><div><div class="eyebrow">Deterministic source derivatives</div><h2>Convert data</h2><p>Create CSV, Parquet, metadata, and codebook outputs, then read them back and verify every cell against the source.</p></div></div><div class="card"><div class="row"><div class="field wide"><label>Source file</label><input id="convert-source" type="text" value="${esc(dataset.source||'')}"></div></div><div class="row"><label class="check"><input id="convert-csv" type="checkbox" checked> CSV</label><label class="check"><input id="convert-parquet" type="checkbox" checked> Parquet</label><label class="check"><input id="convert-labeled" type="checkbox"> Apply source value labels</label></div><div class="row"><div class="field"><label>Output stem (optional)</label><input id="convert-out" type="text" placeholder="Defaults to dataset.main_name"></div><div class="field"><label>CSV missing token</label><input id="convert-na" type="text" value="__RRG_NA__"></div></div><div class="actions"><button class="btn primary" id="convert-run">Convert and verify</button></div><div id="convert-result"></div></div>`;
  document.getElementById('convert-run').onclick=event=>busy(event.currentTarget,'Converting…',async()=>{const formats=[];if(checked('convert-csv'))formats.push('csv');if(checked('convert-parquet'))formats.push('parquet');if(!formats.length)throw new Error('Select at least one format.');const result=await post('/api/convert',{source:value('convert-source'),out:value('convert-out'),formats,labeled:checked('convert-labeled'),na_token:value('convert-na')});const rows=result.outputs.map(output=>`<tr><td>${esc(output.format)}</td><td>${esc(output.name)}</td><td>${output.verify.ok?pill(true,'verified'):pill(false,'mismatch')}</td><td>${esc(output.verify.exact?'bit-for-bit':`max Δ ${output.verify.max_numeric_diff}`)}</td></tr>`).join('');document.getElementById('convert-result').innerHTML=`${result.all_verified?banner('ok','All derivatives verified against the source.'):banner('bad','At least one derivative did not verify.')}<table><thead><tr><th>Format</th><th>File</th><th>Status</th><th>Detail</th></tr></thead><tbody>${rows}</tbody></table>`;toast('Conversion complete')}).catch(error=>{toast(error.message,true);document.getElementById('convert-result').innerHTML=banner('bad',error.message)});
}

function stageOptions(enabledOnly=false){return DATA.stages.filter(stage=>!enabledOnly||stage.enabled).map(stage=>`<option value="${esc(stage.id)}">${esc(stage.id)}${stage.enabled?'':' — disabled'}</option>`).join('')}
function updateModels(stageId,selectId){const stage=DATA.stages.find(item=>item.id===stageId);const select=document.getElementById(selectId);select.innerHTML=(stage?.models||[]).map(item=>`<option value="${esc(item.model)}">${esc(item.model)} · ${esc(item.type||'untyped')}</option>`).join('')||'<option value="">No configured models</option>'}
function renderBuild(){app.innerHTML=`<div class="card hero"><div><div class="eyebrow">Build → lint → publish</div><h2>Build package</h2><p>Packages are assembled in temporary staging and reach the operator directory only after the stage-specific blinding gate passes.</p></div></div><div class="card"><div class="row"><div class="field"><label>Stage</label><select id="build-stage">${stageOptions()}</select></div><div class="field"><label>Model</label><select id="build-model"></select></div><div class="field"><label>Run label (optional)</label><input id="build-label" type="text"></div></div><div id="build-blocker"></div><div class="row"><label class="check"><input id="build-dry" type="checkbox"> Dry run (publish nothing)</label><label class="check"><input id="build-force" type="checkbox"> Force lint override (recorded)</label></div><div class="actions"><button class="btn primary" id="build-run">Build package</button></div><div id="build-result"></div></div>`;
  const stage=document.getElementById('build-stage');const sync=()=>{updateModels(stage.value,'build-model');const item=DATA.stages.find(x=>x.id===stage.value);document.getElementById('build-blocker').innerHTML=!item.enabled?banner('warn',item.blocked_reason||'This stage is disabled.'):'';document.getElementById('build-run').disabled=!item.enabled};stage.onchange=sync;sync();
  document.getElementById('build-run').onclick=event=>busy(event.currentTarget,'Building…',async()=>{const result=await post('/api/package',{stage:stage.value,model:value('build-model'),label:value('build-label'),dry_run:checked('build-dry'),force:checked('build-force')});const lint=result.lint;const findings=[...(lint.hard_fails||[]),...(lint.flags||[])].map(item=>`<li><b>${esc(item.check)}</b>: ${esc(item.message)} ${esc((item.items||[]).join(' · '))}</li>`).join('');document.getElementById('build-result').innerHTML=`${result.blocked?banner('bad','Dispatch blocked by blinding lint.'):banner('ok',result.dry_run?'Dry run passed; nothing was published.':'Package published and output folder prepared.')}<p><b>Package:</b> <code>${esc(result.package_dir)}</code></p><p><b>Output:</b> <code>${esc(result.output_folder)}</code></p>${findings?`<ul>${findings}</ul>`:''}<details><summary>Provenance preview</summary><pre>${esc(JSON.stringify(result.provenance,null,2))}</pre></details>`;toast(result.dry_run?'Dry run passed':'Package built');if(result.published)DATA=await api('/api/bootstrap')}).catch(error=>{toast(error.message,true);document.getElementById('build-result').innerHTML=banner('bad',error.message)});
}

function renderPrompts(){app.innerHTML=`<div class="card hero"><div><div class="eyebrow">Model-facing turns</div><h2>Prompt renderer</h2><p>Cartridge placeholders and optional modules are resolved here. Operator reminders remain visually separated from paste-ready turns.</p></div></div><div class="card"><div class="row"><div class="field"><label>Stage</label><select id="prompt-stage">${stageOptions()}</select></div><div class="field"><label>Model</label><select id="prompt-model"></select></div><div class="field"><label>Method discussion mode</label><select id="prompt-mode"><option value="discuss">With discussion</option><option value="nodiscuss">Operator-reviewed lock</option></select></div></div><div class="actions"><button class="btn primary" id="prompt-render">Render prompt</button></div><div id="prompt-result"></div></div>`;
  const stage=document.getElementById('prompt-stage');const sync=()=>updateModels(stage.value,'prompt-model');stage.onchange=sync;sync();document.getElementById('prompt-render').onclick=event=>busy(event.currentTarget,'Rendering…',async()=>{const result=await api('/api/prompt',{stage:stage.value,model:value('prompt-model')||'PreviewModel',mode:value('prompt-mode')});document.getElementById('prompt-result').innerHTML=`<p class="mut">Source: <code>${esc(result.source)}</code> · Output: <code>${esc(result.output_folder)}</code> · Report: <code>${esc(result.report_name)}</code></p>${result.turns.map((turn,index)=>`<details class="turn" ${index===0?'open':''}><summary>Turn ${index+1} — ${esc(turn.title)}</summary><pre>${esc(turn.text)}</pre></details>`).join('')}${result.reminders?`<details class="turn"><summary>Operator reminders — do not paste</summary><pre>${esc(result.reminders)}</pre></details>`:''}`}).catch(error=>{toast(error.message,true);document.getElementById('prompt-result').innerHTML=banner('bad',error.message)});
}

function renderRuns(){const rows=DATA.runs.map(run=>`<tr class="clickable" data-run="${esc(run.path)}"><td>${stageChip(run.stage)}</td><td>${esc(run.model)}</td><td>${pill(run.returned,run.returned?'returned':'empty')}</td><td>${pill(run.graded,run.graded?'graded':'pending')}</td><td>${run.file_count}</td></tr>`).join('');app.innerHTML=`<div class="card hero"><div><div class="eyebrow">Operator-side outputs</div><h2>Runs</h2><p>Browse validator outputs only. The results key and private/operator-only directories are excluded from this view.</p></div><button class="btn" id="runs-refresh">Refresh</button></div><div class="card">${rows?`<table><thead><tr><th>Stage</th><th>Model/run</th><th>Returned</th><th>Graded</th><th>Files</th></tr></thead><tbody>${rows}</tbody></table>`:'<div class="empty">No validator run folders found.</div>'}</div><div id="run-detail"></div>`;
  document.querySelectorAll('[data-run]').forEach(row=>row.onclick=()=>loadRun(row.dataset.run));document.getElementById('runs-refresh').onclick=async()=>{DATA=await api('/api/bootstrap');renderRuns()};
}
async function loadRun(run){selectedRun=run;const detail=await api('/api/run',{run});const buttons=detail.files.map(file=>`<button data-file="${esc(file.path)}">${esc(file.path)} <span class="mut">${Math.ceil(file.size/1024)} KB</span></button>`).join('');document.getElementById('run-detail').innerHTML=`<div class="card"><h2>${esc(detail.name)}</h2><p class="mut">${stageChip(detail.stage)} · ${detail.file_count} files</p><div class="split"><div class="file-list">${buttons||'<div class="empty">Empty run folder</div>'}</div><div id="file-preview" class="empty">Select a file to preview.</div></div></div>`;document.querySelectorAll('[data-file]').forEach(button=>button.onclick=async()=>{document.querySelectorAll('[data-file]').forEach(item=>item.classList.remove('active'));button.classList.add('active');const result=await api('/api/file',{run,file:button.dataset.file});const target=document.getElementById('file-preview');if(result.kind==='image')target.innerHTML=`<img src="${result.data_url}" alt="${esc(button.dataset.file)}">`;else if(result.kind==='text')target.innerHTML=`<pre>${esc(result.text)}</pre>`;else target.innerHTML=`<div class="empty">${esc(result.message)}</div>`})}

function renderCompare(){const returned=DATA.runs.filter(run=>run.returned);const runOptions=returned.map(run=>`<option value="${esc(run.path)}">${esc(run.stage)} · ${esc(run.model)}</option>`).join('');app.innerHTML=`<div class="card hero"><div><div class="eyebrow">Question-level visual review</div><h2>Compare</h2><p>View validator and held-back original figures side by side. Notes remain operator-only and flow into review context.</p></div></div><div class="card"><div class="field"><label>Returned run</label><select id="compare-run">${runOptions||'<option value="">No returned runs</option>'}</select></div><div class="qnav" id="compare-qnav">${DATA.questions.map(question=>`<button data-q="${question.new}" title="${esc(question.topic)}">${question.new}</button>`).join('')}</div><div id="compare-result"></div></div>`;document.querySelectorAll('[data-q]').forEach(button=>button.onclick=()=>loadCompare(Number(button.dataset.q)));document.getElementById('compare-run').onchange=()=>loadCompare(selectedQuestion);if(returned.length)loadCompare(DATA.questions[0]?.new||1)}
async function loadCompare(question){selectedQuestion=question;document.querySelectorAll('[data-q]').forEach(button=>button.classList.toggle('active',Number(button.dataset.q)===question));const run=value('compare-run');if(!run)return;const result=await api('/api/compare',{run,question});const figures=items=>items.map(item=>`<figure><img src="${item.data_url}" alt="${esc(item.name)}"><figcaption class="mut">${esc(item.name)}</figcaption></figure>`).join('')||'<div class="empty">No matching figure.</div>';document.getElementById('compare-result').innerHTML=`<h3>Q${result.question.new} — ${esc(result.question.topic)}</h3><div class="fig-grid"><section><h3>Validator</h3>${figures(result.validator)}</section><section><h3>Original key</h3>${figures(result.original)}</section></div><label>Operator note</label><textarea id="compare-note">${esc(result.note||'')}</textarea><div class="actions"><button class="btn primary" id="compare-save">Save note</button></div>`;document.getElementById('compare-save').onclick=async()=>{await post('/api/note',{run,question,text:value('compare-note')});toast('Comparison note saved')}}

function ocell(ok){return ok?'<span class="pill ok">✓</span>':'<span class="pill bad">—</span>'}
async function renderOrigin(){
  loading('Loading origin…');
  let data;
  try{data=await api('/api/origin')}catch(error){app.innerHTML=`<div class="card hero"><div><div class="eyebrow">Held-back source of truth</div><h2>Origin report</h2></div></div><div class="card">${banner('bad',error.message)}</div>`;return}
  const counts=data.counts;
  const allGood=counts.total>0&&counts.ok===counts.total;
  const summary=counts.total===0?banner('warn','No question map found — add questions_map.yaml to verify separation.'):(allGood?banner('ok',`All ${counts.total} questions are functionally separated across the question, protocol, and origin-key documents — each can be scored on its own.`):banner('bad',`${counts.total-counts.ok} of ${counts.total} questions are missing an isolated section in at least one document. Resolve these before grading.`));
  const rows=data.rows.map(row=>`<tr class="clickable" data-orq="${row.new}"><td>${row.new}${row.original!==row.new?`<span class="mut"> · orig ${row.original}</span>`:''}</td><td>${esc(row.topic)}</td><td>${ocell(row.has_question)}</td><td>${ocell(row.has_protocol)}</td><td>${ocell(row.has_origin)}</td><td>${row.ok?pill(true,'scoreable'):'<span class="pill bad">gap</span>'}</td></tr>`).join('');
  app.innerHTML=`<div class="card hero"><div><div class="eyebrow">Held-back source of truth</div><h2>Origin report</h2><p>The origin report is withheld from every package. Confirm each question is split into its own section so the scorecard can grade it independently, read the report, and draft the result-free methodology sent to replication.</p></div><div class="pill">${esc(data.results_key)}</div></div>${summary}<div class="card"><h2>Per-question separation</h2><table><thead><tr><th>Q</th><th>Topic</th><th>Question</th><th>Protocol</th><th>Origin key</th><th>Status</th></tr></thead><tbody>${rows||'<tr><td colspan="6"><div class="empty">No questions configured.</div></td></tr>'}</tbody></table><p class="mut">Question = <code>${esc(data.questions_file.name||'QUESTIONS.md')}</code>, Protocol = <code>${esc(data.protocol.name||'ANALYSIS_PROTOCOL_OG.md')}</code>, Origin key = <code>${esc(data.summary.name||'(none)')}</code>. Origin sections are matched exactly as the scorecard extracts them (## Q&lt;original&gt;).</p><div id="origin-detail" class="empty">Select a question to preview its three sections.</div></div><div class="card"><h2>Origin report — ${esc(data.report.name||'not found')}</h2><div id="origin-report"><div class="empty">Loading report…</div></div></div><div class="card"><h2>Draft the methodology document</h2><p class="mut">Render a result-free prompt to send to the origin model (or your origin-author stand-in). Paste the returned protocol to write <code>${esc(data.protocol.path||'shared/ANALYSIS_PROTOCOL_OG.md')}</code> — the methods doc revealed only in replication.</p><div class="actions"><button class="btn" id="origin-gen">Render generation prompt</button></div><div id="origin-prompt"></div><label>Returned protocol (paste here)</label><textarea id="origin-protocol" placeholder="Paste the result-free protocol returned by the origin model…"></textarea><div class="actions"><button class="btn primary" id="origin-save">Save as protocol</button></div><div id="origin-save-result"></div></div>`;
  const detail=document.getElementById('origin-detail');
  document.querySelectorAll('[data-orq]').forEach(tr=>tr.onclick=()=>{
    document.querySelectorAll('[data-orq]').forEach(item=>item.classList.remove('active'));tr.classList.add('active');
    const row=data.rows.find(item=>item.new===Number(tr.dataset.orq));
    const block=(title,ok,text)=>`<section><h3>${esc(title)} ${ok?'<span class="pill ok">✓</span>':'<span class="pill bad">missing</span>'}</h3>${text&&text.trim()?`<pre>${esc(text)}</pre>`:'<div class="empty">No isolated section for this question.</div>'}</section>`;
    detail.className='';
    detail.innerHTML=`<h3>Q${row.new} — ${esc(row.topic)}</h3>${block('Question · '+(data.questions_file.name||'QUESTIONS.md'),row.has_question,row.question)}${block('Protocol · '+(data.protocol.name||'ANALYSIS_PROTOCOL_OG.md'),row.has_protocol,row.protocol)}${block('Origin key · '+(data.summary.name||'none'),row.has_origin,row.origin)}`;
  });
  loadOriginReport();
  document.getElementById('origin-gen').onclick=event=>busy(event.currentTarget,'Rendering…',async()=>{
    const result=await api('/api/origin/methodology_prompt');
    document.getElementById('origin-prompt').innerHTML=`<p class="mut">Source: <code>${esc(result.source)}</code> · writes to <code>${esc(result.target)}</code></p><textarea id="origin-prompt-text" readonly>${esc(result.text)}</textarea><div class="actions"><button class="btn" id="origin-copy">Copy prompt</button></div>`;
    document.getElementById('origin-copy').onclick=()=>{navigator.clipboard&&navigator.clipboard.writeText(result.text);toast('Prompt copied')};
  }).catch(error=>toast(error.message,true));
  document.getElementById('origin-save').onclick=event=>busy(event.currentTarget,'Saving…',async()=>{
    const text=value('origin-protocol');
    if(!text.trim()){toast('Paste the returned protocol first',true);return}
    const result=await post('/api/origin/methodology',{text});
    const warn=result.warnings&&result.warnings.length?`<div class="banner warn">Saved, but ${result.warnings.length} line(s) look like results — review for leaks.</div><ul class="mut">${result.warnings.slice(0,8).map(item=>`<li>L${item.line} (${esc(item.reason)}): ${esc(item.text)}</li>`).join('')}</ul>`:banner('ok','No result-like content detected.');
    document.getElementById('origin-save-result').innerHTML=`${banner('ok','Wrote '+result.written)}${warn}`;
    toast('Protocol saved');renderOrigin();
  }).catch(error=>{toast(error.message,true);document.getElementById('origin-save-result').innerHTML=banner('bad',error.message)});
}
async function loadOriginReport(){
  const target=document.getElementById('origin-report');if(!target)return;
  try{
    const report=await api('/api/origin/report');
    if(report.kind==='pdf')target.innerHTML=`<iframe class="pdf" src="/api/origin/report.pdf?token=${encodeURIComponent(TOKEN)}" title="Origin report"></iframe><p class="mut">If the preview stays blank, open <code>${esc(report.abs)}</code> directly.</p>`;
    else if(report.kind==='text')target.innerHTML=`<pre>${esc(report.text)}</pre>`;
    else if(report.kind==='toolarge')target.innerHTML=`<div class="empty">Report is ${Math.ceil(report.size/1048576)} MB — too large to preview inline. Open <code>${esc(report.abs)}</code> directly.</div>`;
    else target.innerHTML=`<div class="empty">No inline preview for ${esc(report.name)}. Open <code>${esc(report.abs)}</code> directly.</div>`;
  }catch(error){target.innerHTML=`<div class="empty">${esc(error.message)}</div>`}
}
function renderScorecards(){const runOptions=DATA.runs.map(run=>`<option value="${esc(run.path)}">${esc(run.stage)} · ${esc(run.model)}</option>`).join('');const cards=DATA.scorecards.map(card=>`<tr class="clickable" data-card="${esc(card.path)}"><td>${esc(card.name)}</td><td>${Math.ceil(card.size/1024)} KB</td></tr>`).join('');app.innerHTML=`<div class="card hero"><div><div class="eyebrow">Human grading only</div><h2>Scorecards</h2><p>Generate a provisional side-by-side scaffold. The engine never assigns final verdicts.</p></div></div><div class="card"><div class="row"><div class="field"><label>Run</label><select id="score-run">${runOptions||'<option value="">No runs</option>'}</select></div><div class="field"><label>Stage</label><select id="score-stage">${stageOptions()}</select></div><div class="field"><label>Model label</label><input id="score-model" type="text"></div><div class="field"><label>License</label><input id="score-license" type="text" value="record-at-run-time"></div></div><div class="actions"><button class="btn primary" id="score-generate">Generate scaffold</button></div><div id="score-generate-result"></div></div><div class="card"><h2>Existing scorecards</h2>${cards?`<table><tbody>${cards}</tbody></table>`:'<div class="empty">No scorecards yet.</div>'}</div><div id="score-preview"></div>`;
  const runSelect=document.getElementById('score-run');const sync=()=>{const run=DATA.runs.find(item=>item.path===runSelect.value);if(run){document.getElementById('score-stage').value=run.stage;document.getElementById('score-model').value=run.model}};runSelect.onchange=sync;sync();document.getElementById('score-generate').onclick=event=>busy(event.currentTarget,'Generating…',async()=>{const result=await post('/api/scorecard',{run:value('score-run'),stage:value('score-stage'),model:value('score-model'),license:value('score-license')});document.getElementById('score-generate-result').innerHTML=banner('ok',`Created ${result.path}; all ${result.questions} verdicts remain provisional.`);DATA=await api('/api/bootstrap');toast('Scorecard scaffold generated')}).catch(error=>{toast(error.message,true);document.getElementById('score-generate-result').innerHTML=banner('bad',error.message)});document.querySelectorAll('[data-card]').forEach(row=>row.onclick=async()=>{const result=await api('/api/scorecard',{path:row.dataset.card});document.getElementById('score-preview').innerHTML=`<div class="card"><h2>${esc(result.path)}</h2><pre>${esc(result.text)}</pre></div>`})}

let REVIEW=null;
function renderReview(){
  const returned=DATA.runs.filter(run=>run.returned);
  const runOptions=returned.map(run=>`<option value="${esc(run.path)}">${esc(run.stage)} · ${esc(run.model)}${run.graded?' ✓':''}</option>`).join('');
  const cards=(DATA.scorecards||[]).map(card=>`<tr><td>${esc(card.name)}</td><td>${Math.ceil(card.size/1024)} KB</td><td>${card.protected?pill(true,'finalized'):'<span class="pill">draft</span>'}</td><td><button class="btn" data-card-view="${esc(card.path)}">View</button> <button class="btn danger" data-card-del="${esc(card.path)}"${card.protected?' disabled title="Reopen the run to delete"':''}>Delete</button></td></tr>`).join('');
  app.innerHTML=`<div class="card hero"><div><div class="eyebrow">Compare → grade → scorecard</div><h2>Review &amp; Grade</h2><p>Put the held-back original beside the validator answer for each question, confirm a verdict, then finalize to a scorecard. A run counts as graded only once every question is confirmed by you.</p></div></div><div class="card"><div class="field"><label>Returned run</label><select id="review-run">${runOptions||'<option value="">No returned runs</option>'}</select></div><div id="review-body">${returned.length?'<div class="empty">Loading…</div>':'<div class="empty">No returned validator runs yet. Build and dispatch a package, then import the returned output folder.</div>'}</div></div><div class="card"><h2>Scorecards</h2>${cards?`<table><thead><tr><th>Scorecard</th><th>Size</th><th>State</th><th></th></tr></thead><tbody>${cards}</tbody></table>`:'<div class="empty">No scorecards yet. Finalize a fully-graded run to create one.</div>'}<div id="review-card-preview"></div></div>`;
  document.querySelectorAll('[data-card-view]').forEach(button=>button.onclick=async()=>{const result=await api('/api/scorecard',{path:button.dataset.cardView});document.getElementById('review-card-preview').innerHTML=`<div class="card"><h2>${esc(result.path)}</h2><pre>${esc(result.text)}</pre></div>`});
  document.querySelectorAll('[data-card-del]').forEach(button=>button.onclick=event=>busy(event.currentTarget,'Deleting…',async()=>{await post('/api/scorecard/delete',{path:button.dataset.cardDel});toast('Scorecard deleted');DATA=await api('/api/bootstrap');renderReview()}).catch(error=>toast(error.message,true)));
  const runSelect=document.getElementById('review-run');
  if(returned.length){runSelect.onchange=()=>loadReviewRun(runSelect.value);loadReviewRun(returned.some(run=>run.path===selectedRun)?selectedRun:returned[0].path)}
}
async function loadReviewRun(run){
  selectedRun=run;document.getElementById('review-run').value=run;
  REVIEW=await api('/api/grading',{run});
  const done=REVIEW.verdicts.filter(item=>item.confirmed).length;
  const status=REVIEW.graded?banner('ok',`All ${REVIEW.total} questions confirmed.${REVIEW.finalized?' Finalized scorecard: '+esc(REVIEW.scorecard):' Ready to finalize.'}`):banner('warn',`${done} / ${REVIEW.total} questions confirmed — grading is incomplete.`);
  const qnav=REVIEW.verdicts.map(item=>`<button data-rq="${item.new}" class="${item.confirmed?'done':''}" title="${esc(item.topic)}">${item.new}</button>`).join('');
  const actions=`<div class="actions">${REVIEW.finalized?'<button class="btn" id="review-reopen">Reopen for editing</button>':`<button class="btn primary" id="review-finalize"${REVIEW.graded?'':' disabled'}>Finalize → scorecard</button>`}<button class="btn danger" id="review-del-grading"${REVIEW.finalized?' disabled title="Reopen first"':''}>Discard grading</button></div>`;
  document.getElementById('review-body').innerHTML=`${status}<div class="qnav" id="review-qnav">${qnav}</div><div id="review-q"></div>${actions}`;
  document.querySelectorAll('[data-rq]').forEach(button=>button.onclick=()=>loadReviewQuestion(Number(button.dataset.rq)));
  const finalize=document.getElementById('review-finalize');if(finalize)finalize.onclick=event=>busy(event.currentTarget,'Finalizing…',async()=>{await post('/api/grading/finalize',{run});toast('Scorecard created');DATA=await api('/api/bootstrap');renderReview()}).catch(error=>toast(error.message,true));
  const reopen=document.getElementById('review-reopen');if(reopen)reopen.onclick=event=>busy(event.currentTarget,'Reopening…',async()=>{await post('/api/grading/reopen',{run});toast('Reopened for editing');DATA=await api('/api/bootstrap');loadReviewRun(run)}).catch(error=>toast(error.message,true));
  const discard=document.getElementById('review-del-grading');if(discard)discard.onclick=event=>busy(event.currentTarget,'Discarding…',async()=>{await post('/api/grading/delete',{run});toast('Grading discarded');DATA=await api('/api/bootstrap');loadReviewRun(run)}).catch(error=>toast(error.message,true));
  loadReviewQuestion(REVIEW.verdicts.some(item=>item.new===selectedQuestion)?selectedQuestion:(REVIEW.verdicts[0]?REVIEW.verdicts[0].new:1));
}
async function loadReviewQuestion(question){
  selectedQuestion=question;
  document.querySelectorAll('[data-rq]').forEach(button=>button.classList.toggle('active',Number(button.dataset.rq)===question));
  const run=selectedRun;const result=await api('/api/compare',{run,question});
  const figures=items=>(items||[]).map(item=>`<figure><img src="${item.data_url}" alt="${esc(item.name)}"><figcaption class="mut">${esc(item.name)}</figcaption></figure>`).join('');
  const column=(title,text,figs)=>`<section><h3>${esc(title)}</h3>${text&&text.trim()?`<pre>${esc(text)}</pre>`:'<div class="empty">No text material.</div>'}${figs?`<div class="figs">${figs}</div>`:''}</section>`;
  const legend=(result.legend||[]).map(verdict=>`<option value="${esc(verdict)}"${result.verdict===verdict?' selected':''}>${esc(verdict)}</option>`).join('');
  document.getElementById('review-q').innerHTML=`<h3>Q${result.question.new} — ${esc(result.question.topic)} ${result.confirmed?'<span class="pill ok">confirmed</span>':'<span class="pill">unconfirmed</span>'}</h3><div class="grade-cols">${column('Original answer',result.original_text,figures(result.original))}${column('Validator answer',result.validator_text,figures(result.validator))}<section><h3>Verdict</h3><label>Verdict</label><select id="review-verdict"><option value="">— select —</option>${legend}</select><label>Grader note</label><textarea id="review-note">${esc(result.note||'')}</textarea><div class="actions"><button class="btn primary" id="review-confirm">Confirm verdict</button><button class="btn" id="review-clear">Clear</button></div></section></div>`;
  document.getElementById('review-confirm').onclick=event=>busy(event.currentTarget,'Saving…',async()=>{const verdict=value('review-verdict');if(!verdict){toast('Pick a verdict first',true);return}await post('/api/grading/verdict',{run,question,verdict,note:value('review-note'),confirmed:true});toast('Verdict confirmed');loadReviewRun(run)}).catch(error=>toast(error.message,true));
  document.getElementById('review-clear').onclick=event=>busy(event.currentTarget,'Clearing…',async()=>{await post('/api/grading/verdict',{run,question,verdict:'',note:'',confirmed:false});toast('Verdict cleared');loadReviewRun(run)}).catch(error=>toast(error.message,true));
}

refresh().catch(error=>{app.innerHTML=`<div class="card">${banner('bad',error.message)}</div>`});
