const TOKEN=document.querySelector('meta[name="rrg-token"]').content;
const app=document.getElementById('app');
let DATA=null;
let VIEW='dashboard';
let selectedRun='';
let selectedQuestion=1;

const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const qs=(obj={})=>new URLSearchParams(Object.entries(obj).filter(([,value])=>value!==undefined&&value!==null&&value!=='')).toString();
async function api(path,params){const response=await fetch(path+(params?'?'+qs(params):''),{headers:{'X-RRG-Token':TOKEN}});const data=await response.json();if(!response.ok||data.error)throw new Error(data.error||`HTTP ${response.status}`);return data}
async function post(path,payload){const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-RRG-Token':TOKEN},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok||data.error)throw new Error(data.error||`HTTP ${response.status}`);return data}
function toast(message,bad=false){const node=document.getElementById('toast');node.textContent=message;node.className='show'+(bad?' bad':'');setTimeout(()=>node.className='',2600)}
function stageIndex(id){const index=DATA.stages.findIndex(stage=>stage.id===id);return Math.max(0,index)%6}
function stageChip(id){return `<span class="stage stage-${stageIndex(id)}">${esc(id)}</span>`}
function pill(value,label=value?'yes':'no'){return `<span class="pill ${value?'ok':''}">${esc(label)}</span>`}
function banner(type,text){return `<div class="banner ${type}">${esc(text)}</div>`}
function loading(text='Loading…'){app.innerHTML=`<div class="card loading">${esc(text)}</div>`}
function value(id){return document.getElementById(id)?.value??''}
function checked(id){return !!document.getElementById(id)?.checked}
function lines(text){return String(text||'').split('\n').map(item=>item.trim()).filter(Boolean)}
function figStem(s){return String(s).split('/').pop().replace(/\.[^.]+$/,'').trim().toLowerCase()}
function highlightStats(html,marks,cls){
  const known=new Set((marks||[]).filter(Boolean));
  const NUM='(?:\\d[\\d,]*(?:\\.\\d+)?|\\.\\d+)';
  const re=new RegExp('[~≈+\\-−]?'+NUM+'(?:\\s*[–—-]\\s*'+NUM+')?%?','g');
  return html.replace(/(<[^>]*>)|([^<]+)/g,(whole,tag,text)=>{
    if(tag)return tag;
    return text.replace(re,(m,offset,full)=>{
      const before=full[offset-1],after=full[offset+m.length];
      if(before&&/[\w.]/.test(before))return m;
      if(after&&/\w/.test(after))return m;
      const core=m.replace(/^[~≈+\-−]/,'');
      const norm=core.replace(/%$/,'');
      if(known.has(core)||known.has(norm)||known.has(norm.replace(/,/g,'')))return `<span class="${cls}">${m}</span>`;
      const digits=norm.replace(/[,–—-]/g,'').replace('.','');
      const statLike=core.indexOf('.')>=0||core.indexOf('%')>=0||core.indexOf(',')>=0||digits.length>=3;
      return statLike?`<span class="v-extra">${m}</span>`:m;
    });
  });
}
function md(source){
  if(!source)return '';
  const e=s=>s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
  const inline=t=>{t=e(t);t=t.replace(/!\[([^\]]*)\]\(([^)\s]+)[^)]*\)/g,(m,alt,src)=>`<a class="figref" data-fig="${figStem(src)}">[figure: ${alt||figStem(src)}]</a>`);t=t.replace(/\[([^\]]+)\]\((https?:[^)\s]+)\)/g,'<a href="$2" target="_blank" rel="noreferrer">$1</a>');t=t.replace(/\[([^\]]+)\]\([^)]*\)/g,'$1');t=t.replace(/`([^`]+)`/g,(m,p1)=>/fig|chart|plot|table/i.test(p1)?`<a class="figref" data-fig="${figStem(p1)}">${p1}</a>`:`<code>${p1}</code>`);t=t.replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>');t=t.replace(/(^|[^*])\*([^*\n]+)\*/g,'$1<em>$2</em>');return t};
  const rows=String(source).replace(/\r\n?/g,'\n').split('\n');let html='',i=0,ul=false,ol=false;
  const close=()=>{if(ul){html+='</ul>';ul=false}if(ol){html+='</ol>';ol=false}};
  while(i<rows.length){let line=rows[i];
    if(/^```/.test(line)){close();const buf=[];i++;while(i<rows.length&&!/^```/.test(rows[i])){buf.push(rows[i]);i++}html+=`<pre>${e(buf.join('\n'))}</pre>`;i++;continue}
    const h=line.match(/^(#{1,6})\s+(.*)$/);if(h){close();const l=Math.min(6,h[1].length);html+=`<h${l}>${inline(h[2])}</h${l}>`;i++;continue}
    if(/^\s*\|/.test(line)){close();const tr=[];while(i<rows.length&&/^\s*\|/.test(rows[i])){tr.push(rows[i]);i++}const cells=r=>r.trim().replace(/^\|/,'').replace(/\|$/,'').split('|').map(c=>c.trim());let t='<table>';tr.forEach((r,ri)=>{if(/^\s*\|?[\s:|-]+\|?\s*$/.test(r))return;const tag=ri===0?'th':'td';t+='<tr>'+cells(r).map(c=>`<${tag}>${inline(c)}</${tag}>`).join('')+'</tr>'});html+=t+'</table>';continue}
    if(/^\s*[-*]\s+/.test(line)){if(!ul){close();html+='<ul>';ul=true}html+=`<li>${inline(line.replace(/^\s*[-*]\s+/,''))}</li>`;i++;continue}
    if(/^\s*\d+\.\s+/.test(line)){if(!ol){close();html+='<ol>';ol=true}html+=`<li>${inline(line.replace(/^\s*\d+\.\s+/,''))}</li>`;i++;continue}
    if(/^\s*$/.test(line)){close();i++;continue}
    close();html+=`<p>${inline(line)}</p>`;i++;}
  close();return html;
}
async function busy(button,label,work){const prior=button.textContent;button.disabled=true;button.textContent=label;try{return await work()}finally{button.disabled=false;button.textContent=prior}}

function applyData(data){DATA=data;document.getElementById('project-name').textContent=DATA.project;document.getElementById('project-root').textContent=DATA.root}
async function refresh(){applyData(await api('/api/bootstrap'));applyHashView();render()}
function render(){({dashboard:renderDashboard,setup:renderSetup,convert:renderConvert,build:renderBuild,prompts:renderPrompts,runs:renderRuns,review:renderReview,origin:renderOrigin,files:renderExplorer,guide:renderGuide,projects:renderProjects}[VIEW]||renderDashboard)()}
function knownViews(){return Array.from(document.querySelectorAll('nav button[data-view]')).map(button=>button.dataset.view)}
function closeNavMenus(){document.querySelectorAll('nav .navgroup[open]').forEach(group=>{group.open=false})}
function setNavActive(view){
  document.querySelectorAll('nav button[data-view]').forEach(item=>item.classList.toggle('active',item.dataset.view===view));
  document.querySelectorAll('nav .navgroup').forEach(group=>group.classList.toggle('active',!!group.querySelector('button.active')));
}
function applyHashView(){const target=location.hash.slice(1);VIEW=knownViews().includes(target)?target:'dashboard';setNavActive(VIEW)}
function activateView(view){VIEW=view;setNavActive(view);closeNavMenus();history.replaceState(null,'','#'+view);render()}
document.querySelectorAll('nav button[data-view]').forEach(button=>button.addEventListener('click',()=>activateView(button.dataset.view)));
document.addEventListener('click',event=>{if(!event.target.closest('nav .navgroup'))closeNavMenus()});
window.addEventListener('hashchange',()=>{if(location.hash.slice(1)!==VIEW){applyHashView();render()}});

function renderProjects(){
  const workspace=DATA.workspace||{enabled:false,projects:[]};
  if(!workspace.enabled){app.innerHTML=`<div class="card hero"><div><div class="eyebrow">Project isolation</div><h2>Projects</h2><p>This GUI is locked to one project. Restart with <code>rrg gui --workspace /path/to/workspace</code> to enable safe project switching and creation.</p></div></div><div class="card">${banner('ok',`Active project: ${DATA.project}`)}<p><code>${esc(DATA.root)}</code></p></div>`;return}
  const rows=workspace.projects.map(project=>`<tr><td><b>${esc(project.name)}</b>${project.error?`<div class="mut">${esc(project.error)}</div>`:''}</td><td><code>${esc(project.root)}</code></td><td>${project.active?pill(true,'active'):(project.valid?pill(false,'ready'):pill(false,'invalid'))}</td><td>${project.active?'':`<button class="btn" data-project-root="${esc(project.root)}" ${project.valid?'':'disabled'}>Open</button>`}</td></tr>`).join('');
  app.innerHTML=`<div class="card hero"><div><div class="eyebrow">Confined workspace</div><h2>Projects</h2><p>Each study keeps separate data, manifests, packages, runs, and withheld results. Switching reloads the full project-scoped interface.</p></div><div class="pill">${esc(workspace.root)}</div></div><div class="card"><h2>Workspace projects</h2><table><thead><tr><th>Project</th><th>Relative root</th><th>Status</th><th></th></tr></thead><tbody>${rows}</tbody></table></div><div class="card"><h2>New project</h2><p class="mut">Create a new child directory inside this workspace from the standard RRG scaffold.</p><div class="row"><div class="field"><label>Project name</label><input id="new-project-name" type="text" placeholder="MovieRatings demo"></div><div class="field"><label>Workspace-relative directory</label><input id="new-project-path" type="text" placeholder="demo_projects/MovieRatings"></div></div><div class="actions"><button class="btn primary" id="new-project-create">Create project</button></div><div id="new-project-result"></div></div>`;
  document.querySelectorAll('[data-project-root]').forEach(button=>button.onclick=event=>busy(event.currentTarget,'Opening…',async()=>{applyData(await post('/api/project/select',{root:button.dataset.projectRoot}));selectedRun='';selectedQuestion=1;activateView('dashboard');toast(`Opened ${DATA.project}`)}).catch(error=>toast(error.message,true)));
  document.getElementById('new-project-create').onclick=event=>busy(event.currentTarget,'Creating…',async()=>{applyData(await post('/api/project/create',{name:value('new-project-name'),path:value('new-project-path')}));selectedRun='';selectedQuestion=1;activateView('setup');toast(`Created ${DATA.project}`)}).catch(error=>{toast(error.message,true);document.getElementById('new-project-result').innerHTML=banner('bad',error.message)});
}

let XRAY=false;
function treeNodeHTML(node){
  if(node.dir){
    if(node.redacted)return `<div class="tnode tredacted">${esc(node.name)}/ <span class="pill">withheld</span></div>`;
    const kids=(node.children||[]).map(treeNodeHTML).join('')||'<div class="tnode mut">empty</div>';
    return `<details class="tdir"><summary>${esc(node.name)}/</summary><div class="tchildren">${kids}</div></details>`;
  }
  if(node.redacted)return `<div class="tnode tredacted">${esc(node.name)} <span class="pill">withheld</span></div>`;
  return `<div class="tnode tfile" data-tpath="${esc(node.path)}">${esc(node.name)} <span class="mut">${Math.ceil((node.size||0)/1024)} KB</span></div>`;
}
async function loadTree(){
  const target=document.getElementById('tree');
  try{const data=await api('/api/tree',{xray:XRAY?'1':'0'});target.innerHTML=data.tree.map(treeNodeHTML).join('')||'<div class="empty">No files.</div>';
    target.querySelectorAll('[data-tpath]').forEach(item=>item.onclick=()=>loadTreeFile(item.dataset.tpath));
  }catch(error){target.innerHTML=banner('bad',error.message)}
}
async function loadTreeFile(path){
  const preview=document.getElementById('tfile-preview');
  document.querySelectorAll('#tree [data-tpath]').forEach(item=>item.classList.toggle('active',item.dataset.tpath===path));
  preview.innerHTML='<div class="empty">Loading…</div>';
  try{const result=await api('/api/tree/file',{path,xray:XRAY?'1':'0'});
    if(result.kind==='image')preview.innerHTML=`<div class="tprev-head">${esc(path)}</div><img src="${result.data_url}" alt="${esc(path)}">`;
    else if(result.kind==='text')preview.innerHTML=`<div class="tprev-head">${esc(path)}</div><pre>${esc(result.text)}</pre>`;
    else preview.innerHTML=`<div class="tprev-head">${esc(path)}</div><div class="empty">${esc(result.message||'No preview.')}</div>`;
  }catch(error){preview.innerHTML=banner('bad',error.message)}
}
async function loadArchivePanel(){
  const target=document.getElementById('archive-list');if(!target)return;
  try{const data=await api('/api/archive');const items=data.items||[];
    if(!items.length){target.innerHTML='<div class="empty">Archive is empty.</div>';return}
    target.innerHTML=`<table><thead><tr><th>Item</th><th>Kind</th><th>Archived</th><th></th></tr></thead><tbody>${items.map(item=>`<tr><td><code>${esc(item.original)}</code></td><td>${pill(false,esc(item.kind))}</td><td class="mut">${esc((item.archived_at||'').slice(0,19).replace('T',' '))}</td><td><button class="btn" data-restore="${esc(item.id)}">Restore</button> <button class="btn danger" data-purge="${esc(item.id)}">Purge</button></td></tr>`).join('')}</tbody></table>`;
    target.querySelectorAll('[data-restore]').forEach(button=>button.onclick=event=>busy(event.currentTarget,'Restoring…',async()=>{await post('/api/archive/restore',{id:button.dataset.restore});toast('Restored');loadArchivePanel();loadTree()}).catch(error=>toast(error.message,true)));
    target.querySelectorAll('[data-purge]').forEach(button=>button.onclick=event=>{if(!confirm('Permanently delete this archived item? This cannot be undone.'))return;busy(event.currentTarget,'Purging…',async()=>{await post('/api/archive/purge',{id:button.dataset.purge});toast('Purged');loadArchivePanel()}).catch(error=>toast(error.message,true))});
  }catch(error){target.innerHTML=banner('bad',error.message)}
}
function renderExplorer(){
  app.innerHTML=`<div class="card hero"><div><div class="eyebrow">Project files</div><h2>Explorer</h2><p>Browse everything in this study. The default view is <b>blinding-aware</b> — withheld regions (origin answer key, private, scorecards) show as redacted placeholders, so you can confirm they exist and stay hidden. Operator x-ray reveals them; it never leaves this screen and does not affect what validators receive.</p></div><label class="check xray-toggle"><input id="xray-toggle" type="checkbox" ${XRAY?'checked':''}> Operator x-ray</label></div>
  <div class="card"><div class="split"><div id="tree" class="file-list tree">Loading…</div><div id="tfile-preview" class="empty">Select a file to preview.</div></div></div>
  <div class="card"><h2>Archive</h2><p class="mut">Items removed anywhere in RRG are moved here, not deleted. Restore returns them to their original path; purge deletes permanently.</p><div id="archive-list">Loading…</div></div>`;
  document.getElementById('xray-toggle').onchange=event=>{XRAY=event.currentTarget.checked;loadTree();const preview=document.getElementById('tfile-preview');preview.innerHTML='<div class="empty">Select a file to preview.</div>'};
  loadTree();loadArchivePanel();
}

const GUIDE_STEPS=[
  {title:'Set up the study &amp; convert data',tabs:'Setup · Convert',
   body:`<p>Fill the cartridge — study identity, dataset, questions, stages, and the per-stage model roster. Then convert the source into CSV/Parquet derivatives; every cell is verified bit-for-bit against the source.</p>`,
   cmd:'rrg convert',
   concept:'Verified data derivatives keep <b>stable names</b> — they are never run_id-suffixed, so the manifest stays reproducible. Preflight must be green before you build.'},
  {title:'Build a blinded package',tabs:'Build',
   body:`<p>RRG assembles the stage package in staging, runs the blinding lint (no withheld file can get in), and on pass writes a <b>self-contained delivery zip</b> with no operator metadata.</p>`,
   cmd:'rrg package --stage robustness --model Gemini',
   concept:'Each build mints an opaque <code>run_id</code> that suffixes the run folder, package dir, and zip — so re-running a model <b>never clobbers</b> prior history.'},
  {title:'Dispatch — move the zip OUT of the project',tabs:'(your runner)',
   body:`<p>Copy the delivery zip to a scratch directory, container, or another machine — anywhere that does <b>not</b> have the project's <code>operator/</code> tree as a parent. This placement is what stops a validator from reaching the answer key.</p>`,
   cmd:'',
   concept:'Isolation by placement (ADR 0001). <b>Never unzip inside <code>operator/</code>.</b> The zip carries a tiny <code>RRG_RUN.txt</code> marker — an opaque id and nothing else.'},
  {title:'Run the validator in isolation',tabs:'Prompts',
   body:`<p>Run the model on the unzipped package. In the GUI, render the staged prompt turns and paste them in order (robustness uses the discuss→lock flow). When finished, zip the validator's output folder — leaving <code>RRG_RUN.txt</code> in it.</p>`,
   cmd:'',
   concept:'The validator only ever sees the package — never the origin results, methodology key, or your operator files.'},
  {title:'Import the results back',tabs:'Build ▸ Import · Runs',
   body:`<p>Drop the returned results zip into RRG. It reads <code>RRG_RUN.txt</code>, looks the <code>run_id</code> up in the provenance log, and auto-resolves the stage, model, and run folder — no manual selection.</p>`,
   cmd:'rrg import returned-results.zip',
   concept:'Auto-resolution re-binds the results to their build. If the marker is missing, fall back to <code>--stage</code> / <code>--model</code>.'},
  {title:'Automatic breach check',tabs:'(runs on import)',
   body:`<p>On import, RRG hashes every returned file against the withheld answer key. A byte-for-byte match means a secret was <b>copied</b> — a near-certain blinding breach: it is flagged and <b>grading is blocked</b> until you acknowledge it. A results source from inside the project tree raises a softer warning.</p>`,
   cmd:'rrg acknowledge-breach --run operator/robustness_Gemini__a1b2c3d4',
   concept:'This guards the <b>return</b> path — complementing the content-lint (guards what is in the package) and isolation (guards reach).'},
  {title:'Review, grade &amp; finalize',tabs:'Review &amp; Grade · Files',
   body:`<p>Compare validator vs origin per question — stats, narratives, figures — and confirm a verdict for each. Finalizing writes a versioned scorecard. Browse everything anytime in the <b>Files</b> tab (blinding-aware, with an operator x-ray toggle); anything you delete goes to the <b>Archive</b>, where you can restore or purge it.</p>`,
   cmd:'rrg runs   # every build and its status: pending / returned / graded / ⚠breach',
   concept:'A run is <b>graded</b> only when every question has a confirmed verdict. Deletion is reversible by default.'},
];
let GUIDE_ACTIVE=0;
function renderGuide(){
  const steps=GUIDE_STEPS.map((step,index)=>`<div class="tl-step${index===GUIDE_ACTIVE?' active':''}" data-step="${index}"><div class="tl-node">${index+1}</div><div class="tl-main"><div class="tl-head">${step.title}<span class="tl-tabs">${step.tabs}</span></div><div class="tl-body">${step.body}${step.cmd?`<pre>${esc(step.cmd)}</pre>`:''}<div class="tl-concept">${step.concept}</div></div></div></div>`).join('');
  app.innerHTML=`<div class="card hero"><div><div class="eyebrow">How RRG works</div><h2>The validation round-trip</h2><p>Seven steps from a blinded package to a finalized scorecard. Click any step to expand it. Each one names the tab to use and the matching <code>rrg</code> command.</p></div></div><div class="card"><div class="timeline">${steps}</div></div>`;
  document.querySelectorAll('.tl-head').forEach(head=>head.onclick=()=>{GUIDE_ACTIVE=Number(head.closest('.tl-step').dataset.step);document.querySelectorAll('.tl-step').forEach(step=>step.classList.toggle('active',Number(step.dataset.step)===GUIDE_ACTIVE))});
}

function renderDashboard(){
  const packages=DATA.stages.reduce((sum,stage)=>sum+stage.packages,0);
  const returned=DATA.stages.reduce((sum,stage)=>sum+stage.returned,0);
  const issues=DATA.preflight.checks.filter(check=>check.severity==='error').length;
  const rows=DATA.stages.map(stage=>`<tr><td>${stageChip(stage.id)}</td><td>${stage.enabled?pill(true,'enabled'):pill(false,'disabled')}</td><td>${esc(stage.opens||'—')}</td><td>${esc(stage.models.map(item=>item.model).join(', ')||'—')}</td><td>${stage.packages}</td><td>${stage.returned}</td><td>${stage.graded}</td></tr>`).join('');
  const checks=DATA.preflight.checks.filter(check=>check.severity!=='ok').map(check=>`<li><span class="pill ${check.severity==='error'?'bad':'warn'}">${esc(check.severity)}</span> ${esc(check.name)} — ${esc(check.detail)}</li>`).join('');
  app.innerHTML=`<div class="card hero"><div><div class="eyebrow">Degrees-of-freedom validation</div><h2>${esc(DATA.project)}</h2><p>One engine for project setup, verified data conversion, blinded package assembly, staged prompts, returned-run review, comparison, and human scorecards.</p></div><button class="btn" id="dash-refresh">Refresh</button></div>
  <div class="grid"><div class="metric"><div class="value">${packages}</div><div class="label">Published packages</div></div><div class="metric"><div class="value">${returned}</div><div class="label">Returned runs</div></div><div class="metric"><div class="value">${issues}</div><div class="label">Blocking preflight issues</div></div></div>
  <div class="card"><h2>Stage status</h2><table><thead><tr><th>Stage</th><th>Status</th><th>Opens</th><th>Models</th><th>Packaged</th><th>Returned</th><th>Graded</th></tr></thead><tbody>${rows}</tbody></table></div>
  <div class="card"><h2>Preflight</h2>${DATA.preflight.ok?banner('ok','All enabled stages and referenced inputs pass preflight.'):banner('bad','The project is not ready; resolve the checks below.')} ${checks?`<ul>${checks}</ul>`:'<p class="mut">No warnings or errors.</p>'}</div>`;
  document.getElementById('dash-refresh').onclick=()=>{loading('Refreshing project…');refresh().catch(error=>{toast(error.message,true);render()})};
}

function renderSetup(){
  const study=DATA.study||{},dataset=study.dataset||{},aux=dataset.aux||{},solution=study.given_solution||{},questions=study.questions||{},held=study.held_constants||{},original=study.original||{},delivery=study.deliverable||{},guide=delivery.method_guide||{};
  const additional=(study.additional||[]).map(item=>[item.name||'',item.file||'',item.note||''].join(' :: ')).join('\n');
  const stageRows=DATA.stages.map((stage,index)=>`<tr><td>${stageChip(stage.id)}</td><td><input type="checkbox" id="stage-enabled-${index}" ${stage.enabled?'checked':''}></td><td><input type="text" id="stage-prompt-${index}" value="${esc(stage.prompt)}"></td><td><textarea id="stage-send-${index}">${esc((stage.send||[]).join('\n'))}</textarea></td><td><input type="text" id="stage-block-${index}" value="${esc(stage.blocked_reason)}"></td></tr>`).join('');
  app.innerHTML=`<div class="card hero"><div><div class="eyebrow">Project cartridge</div><h2>Setup</h2><p>Edit known engine and study fields. Unknown YAML fields are preserved when this form saves.</p></div><div class="pill">${esc(DATA.config_path)} · ${esc(DATA.study_path)}</div></div>
  <div class="card"><h2>Study identity and inputs</h2><div class="row"><div class="field"><label>Project name</label><input id="setup-project" type="text" value="${esc(DATA.project)}"></div><div class="field"><label>Study title</label><input id="setup-title" type="text" value="${esc(study.title||'')}"></div><div class="field"><label>Overview file</label><input id="setup-overview" type="text" value="${esc(study.overview_file||'')}"></div></div>
  <h3>Dataset</h3><div class="row"><div class="field"><label>Authoritative source</label><input id="setup-source" type="text" value="${esc(dataset.source||'')}"></div><div class="field"><label>Analysis-copy stem</label><input id="setup-main" type="text" value="${esc(dataset.main_name||'')}"></div><div class="field"><label>Merge key</label><input id="setup-key" type="text" value="${esc(dataset.merge_key||'')}"></div></div><div class="row"><div class="field"><label>Formats (comma separated)</label><input id="setup-formats" type="text" value="${esc((dataset.formats||[]).join(', '))}"></div><div class="field"><label>Codebook</label><input id="setup-codebook" type="text" value="${esc(dataset.codebook||'')}"></div><div class="field"><label>Metadata sidecar</label><input id="setup-metadata" type="text" value="${esc(dataset.metadata||'')}"></div></div><label>Data-orientation prompt text</label><textarea id="setup-orientation">${esc(dataset.orientation||'')}</textarea>
  <div class="row"><label class="check"><input id="setup-aux-enabled" type="checkbox" ${aux.enabled?'checked':''}> Auxiliary dataset enabled</label><div class="field"><label>Aux name</label><input id="setup-aux-name" type="text" value="${esc(aux.name||'')}"></div><div class="field"><label>Aux file</label><input id="setup-aux-file" type="text" value="${esc(aux.file||'')}"></div><div class="field"><label>Aux note</label><input id="setup-aux-note" type="text" value="${esc(aux.note||'')}"></div></div>
  <h3>Questions and held constants</h3><div class="row"><div class="field"><label>Questions file</label><input id="setup-questions" type="text" value="${esc(questions.file||'')}"></div><div class="field"><label>Question count</label><input id="setup-count" type="number" min="1" value="${esc(questions.count||'')}"></div><div class="field"><label>Question map</label><input id="setup-map" type="text" value="${esc(questions.map||'')}"></div></div><div class="row"><div class="field"><label>Held-constants file</label><input id="setup-held-file" type="text" value="${esc(held.file||'')}"></div><div class="field"><label>Summary</label><input id="setup-held-summary" type="text" value="${esc(held.summary||'')}"></div><div class="field"><label>QA groups</label><input id="setup-held-groups" type="text" value="${esc(held.qa_groups||'')}"></div></div>
  <h3>Original work and supplied solution</h3><div class="row"><div class="field"><label>Original methodology</label><input id="setup-method" type="text" value="${esc(original.methodology_file||'')}"></div><div class="field"><label>Withheld results key</label><input id="setup-keydir" type="text" value="${esc(original.results_key||'')}"></div><div class="field"><label>Origin model</label><input id="setup-origin-model" type="text" value="${esc(original.model||'')}"></div><div class="field"><label>Origin vendor</label><input id="setup-origin-vendor" type="text" value="${esc(original.vendor||'')}"></div></div><label class="check"><input id="setup-solution-enabled" type="checkbox" ${solution.enabled?'checked':''}> Fixed/supplied solution enabled</label><div class="row"><div class="field"><label>Solution glossary</label><input id="setup-solution-glossary" type="text" value="${esc(solution.glossary||'')}"></div><div class="field"><label>Solution artifacts (one per line)</label><textarea id="setup-solution-artifacts">${esc((solution.artifacts||[]).join('\n'))}</textarea></div><div class="field"><label>Solution instruction</label><textarea id="setup-solution-note">${esc(solution.note||'')}</textarea></div></div><label>Additional inputs: name :: file :: note</label><textarea id="setup-additional">${esc(additional)}</textarea>
  <h3>Deliverable</h3><div class="row"><div class="field"><label>Report filename template</label><input id="setup-report" type="text" value="${esc(delivery.report_name||'')}"></div><label class="check"><input id="setup-guide-enabled" type="checkbox" ${guide.enabled?'checked':''}> Method guide enabled</label><div class="field"><label>Guide name</label><input id="setup-guide-name" type="text" value="${esc(guide.name||'')}"></div><div class="field"><label>Guide file</label><input id="setup-guide-file" type="text" value="${esc(guide.file||'')}"></div></div><label>Reporting specification</label><textarea id="setup-reporting">${esc(delivery.reporting_spec||'')}</textarea></div>
  <div class="card"><h2>Stages</h2><table><thead><tr><th>Stage</th><th>Enabled</th><th>Prompt</th><th>Send tokens/paths</th><th>Blocked reason</th></tr></thead><tbody>${stageRows}</tbody></table></div>
  <div class="card"><h2>Models per stage</h2><p class="mut">Set which models run at each stage. The dispatch slug is substituted into the start command (<code>{model_slug}</code>); leave it blank to skip.</p><div id="roster-editor">${rosterEditorHTML()}</div><label>Dispatch start template</label><input id="setup-dispatch" type="text" value="${esc(DATA.dispatch_start||'')}"><div class="actions"><button class="btn primary" id="setup-save">Save and preflight</button><button class="btn" id="setup-check">Run preflight</button></div><div id="setup-result"></div></div>`;
  wireRosterEditor();
  document.getElementById('setup-save').onclick=event=>busy(event.currentTarget,'Saving…',saveSetup).catch(error=>toast(error.message,true));
  document.getElementById('setup-check').onclick=event=>busy(event.currentTarget,'Checking…',async()=>{const result=await api('/api/preflight');document.getElementById('setup-result').innerHTML=preflightHTML(result)}).catch(error=>toast(error.message,true));
}

function modelRowHTML(stageId,model={},slug=''){return `<div class="rost-row" data-stage="${esc(stageId)}"><input class="rost-model" placeholder="model" value="${esc(model.model||'')}"><input class="rost-vendor" placeholder="vendor" value="${esc(model.vendor||'')}"><input class="rost-type" placeholder="type (open/frontier)" value="${esc(model.type||'')}"><input class="rost-license" placeholder="license" value="${esc(model.license||'')}"><input class="rost-slug" placeholder="dispatch slug" value="${esc(slug)}"><button type="button" class="btn danger rost-del" title="Remove model">×</button></div>`}
function rosterEditorHTML(){const slugs=DATA.dispatch_slugs||{};const labels='<div class="rost-labels"><span>Model</span><span>Vendor</span><span>Type</span><span>License</span><span>Dispatch slug</span><span></span></div>';return DATA.stages.map(stage=>{const models=stage.models||[];const rows=models.map(model=>modelRowHTML(stage.id,model,slugs[model.model]||'')).join('');return `<div class="rost-stage" data-stage="${esc(stage.id)}"><div class="rost-head">${stageChip(stage.id)}<button type="button" class="btn rost-add" data-stage="${esc(stage.id)}">+ Add model</button></div>${models.length?labels:''}<div class="rost-rows">${rows||'<div class="empty">No models configured for this stage.</div>'}</div></div>`}).join('')}
const ROST_LABELS='<div class="rost-labels"><span>Model</span><span>Vendor</span><span>Type</span><span>License</span><span>Dispatch slug</span><span></span></div>';
function wireRosterEditor(){const editor=document.getElementById('roster-editor');if(!editor)return;editor.querySelectorAll('.rost-add').forEach(button=>button.onclick=()=>{const stageEl=button.closest('.rost-stage');const rows=stageEl.querySelector('.rost-rows');const empty=rows.querySelector('.empty');if(empty)empty.remove();if(!stageEl.querySelector('.rost-labels'))rows.insertAdjacentHTML('beforebegin',ROST_LABELS);rows.insertAdjacentHTML('beforeend',modelRowHTML(button.dataset.stage));bindRosterDeletes(editor)});bindRosterDeletes(editor)}
function bindRosterDeletes(editor){editor.querySelectorAll('.rost-del').forEach(button=>button.onclick=()=>{const rows=button.closest('.rost-rows');button.closest('.rost-row').remove();if(!rows.querySelector('.rost-row'))rows.innerHTML='<div class="empty">No models configured for this stage.</div>'})}
function collectRoster(){const roster={},slugs={};DATA.stages.forEach(stage=>{roster[stage.id]=[]});document.querySelectorAll('#roster-editor .rost-row').forEach(row=>{const model=row.querySelector('.rost-model').value.trim();if(!model)return;roster[row.dataset.stage].push({model,vendor:row.querySelector('.rost-vendor').value.trim(),type:row.querySelector('.rost-type').value.trim(),license:row.querySelector('.rost-license').value.trim()});const slug=row.querySelector('.rost-slug').value.trim();if(slug)slugs[model]=slug});return {roster,slugs}}
async function saveSetup(){
  const {roster,slugs}=collectRoster();
  const additional=lines(value('setup-additional')).map(line=>{const [name='',file='',note='']=line.split('::').map(item=>item.trim());return {name,file,note}});
  const stagePatches=DATA.stages.map((stage,index)=>({id:stage.id,enabled:checked(`stage-enabled-${index}`),prompt:value(`stage-prompt-${index}`),send:lines(value(`stage-send-${index}`)),blocked_reason:value(`stage-block-${index}`)}));
  const payload={study:{title:value('setup-title'),overview_file:value('setup-overview'),dataset:{source:value('setup-source'),main_name:value('setup-main'),merge_key:value('setup-key'),formats:value('setup-formats').split(',').map(item=>item.trim()).filter(Boolean),codebook:value('setup-codebook'),metadata:value('setup-metadata'),orientation:value('setup-orientation'),aux:{enabled:checked('setup-aux-enabled'),name:value('setup-aux-name'),file:value('setup-aux-file'),note:value('setup-aux-note')}},given_solution:{enabled:checked('setup-solution-enabled'),glossary:value('setup-solution-glossary'),artifacts:lines(value('setup-solution-artifacts')),note:value('setup-solution-note')},additional,questions:{file:value('setup-questions'),count:Number(value('setup-count')),map:value('setup-map')},held_constants:{file:value('setup-held-file'),summary:value('setup-held-summary'),qa_groups:value('setup-held-groups')},original:{methodology_file:value('setup-method'),results_key:value('setup-keydir'),model:value('setup-origin-model'),vendor:value('setup-origin-vendor')},deliverable:{report_name:value('setup-report'),reporting_spec:value('setup-reporting'),method_guide:{enabled:checked('setup-guide-enabled'),name:value('setup-guide-name'),file:value('setup-guide-file')}}},engine:{project_name:value('setup-project'),stages:stagePatches,roster,model_slugs:slugs,dispatch_start:value('setup-dispatch')}};
  DATA=await post('/api/setup',payload);document.getElementById('project-name').textContent=DATA.project;document.getElementById('project-root').textContent=DATA.root;toast('Project configuration saved');renderSetup();
}
function preflightHTML(result){const rows=result.checks.map(check=>`<tr><td>${check.severity==='ok'?pill(true,'✓'):`<span class="pill ${check.severity==='error'?'bad':'warn'}">${esc(check.severity)}</span>`}</td><td>${esc(check.name)}</td><td>${esc(check.detail)}</td></tr>`).join('');return `${result.ok?banner('ok','Preflight passed.'):banner('bad','Preflight found blocking issues.')}<table><tbody>${rows}</tbody></table>`}

function renderConvert(){const dataset=DATA.dataset||{};app.innerHTML=`<div class="card hero"><div><div class="eyebrow">Deterministic source derivatives</div><h2>Convert data</h2><p>Create CSV, Parquet, metadata, and codebook outputs, then read them back and verify every cell against the source.</p></div></div><div class="card"><div class="row"><div class="field wide"><label>Source file</label><input id="convert-source" type="text" value="${esc(dataset.source||'')}"></div></div><div class="row"><label class="check"><input id="convert-csv" type="checkbox" checked> CSV</label><label class="check"><input id="convert-parquet" type="checkbox" checked> Parquet</label><label class="check"><input id="convert-labeled" type="checkbox"> Apply source value labels</label></div><div class="row"><div class="field"><label>Output stem (optional)</label><input id="convert-out" type="text" placeholder="Defaults to dataset.main_name"></div><div class="field"><label>CSV missing token</label><input id="convert-na" type="text" value="__RRG_NA__"></div></div><div class="actions"><button class="btn primary" id="convert-run">Convert and verify</button></div><div id="convert-result"></div></div>`;
  document.getElementById('convert-run').onclick=event=>busy(event.currentTarget,'Converting…',async()=>{const formats=[];if(checked('convert-csv'))formats.push('csv');if(checked('convert-parquet'))formats.push('parquet');if(!formats.length)throw new Error('Select at least one format.');const result=await post('/api/convert',{source:value('convert-source'),out:value('convert-out'),formats,labeled:checked('convert-labeled'),na_token:value('convert-na')});const rows=result.outputs.map(output=>`<tr><td>${esc(output.format)}</td><td>${esc(output.name)}</td><td>${output.verify.ok?pill(true,'verified'):pill(false,'mismatch')}</td><td>${esc(output.verify.exact?'bit-for-bit':`max Δ ${output.verify.max_numeric_diff}`)}</td></tr>`).join('');document.getElementById('convert-result').innerHTML=`${result.all_verified?banner('ok','All derivatives verified against the source.'):banner('bad','At least one derivative did not verify.')}<table><thead><tr><th>Format</th><th>File</th><th>Status</th><th>Detail</th></tr></thead><tbody>${rows}</tbody></table>`;toast('Conversion complete')}).catch(error=>{toast(error.message,true);document.getElementById('convert-result').innerHTML=banner('bad',error.message)});
}

function stageOptions(enabledOnly=false){return DATA.stages.filter(stage=>!enabledOnly||stage.enabled).map(stage=>`<option value="${esc(stage.id)}">${esc(stage.id)}${stage.enabled?'':' — disabled'}</option>`).join('')}
function updateModels(stageId,selectId){const stage=DATA.stages.find(item=>item.id===stageId);const select=document.getElementById(selectId);select.innerHTML=(stage?.models||[]).map(item=>`<option value="${esc(item.model)}">${esc(item.model)} · ${esc(item.type||'untyped')}</option>`).join('')||'<option value="">No configured models</option>'}
function renderBuild(){app.innerHTML=`<div class="card hero"><div><div class="eyebrow">Build → lint → publish</div><h2>Build package</h2><p>Packages are assembled in temporary staging and reach the operator directory only after the stage-specific blinding gate passes.</p></div></div><div class="card"><div class="row"><div class="field"><label>Stage</label><select id="build-stage">${stageOptions()}</select></div><div class="field"><label>Model</label><select id="build-model"></select></div><div class="field"><label>Run label (optional)</label><input id="build-label" type="text"></div></div><div id="build-blocker"></div><div class="row"><label class="check"><input id="build-dry" type="checkbox"> Dry run (publish nothing)</label><label class="check"><input id="build-force" type="checkbox"> Force lint override (recorded)</label></div><div class="actions"><button class="btn primary" id="build-run">Build package</button></div><div id="build-result"></div></div><div class="card"><h2>Import returned run</h2><p class="mut">After the validator runs <b>in isolation</b> (on the delivered zip, outside this project) and returns its outputs, bring them back into the run folder for review and grading.</p><div class="row"><div class="field"><label>Stage</label><select id="import-stage">${stageOptions()}</select></div><div class="field"><label>Model label</label><input id="import-model" type="text" placeholder="model"></div></div><div class="field wide"><label>Returned folder or .zip (absolute path)</label><input id="import-source" type="text" placeholder="/path/to/returned-output"></div><div class="actions"><button class="btn primary" id="import-run">Import outputs</button></div><div id="import-result"></div></div>`;
  const stage=document.getElementById('build-stage');const sync=()=>{updateModels(stage.value,'build-model');const item=DATA.stages.find(x=>x.id===stage.value);document.getElementById('build-blocker').innerHTML=!item.enabled?banner('warn',item.blocked_reason||'This stage is disabled.'):'';document.getElementById('build-run').disabled=!item.enabled};stage.onchange=sync;sync();
  document.getElementById('build-run').onclick=event=>busy(event.currentTarget,'Building…',async()=>{const result=await post('/api/package',{stage:stage.value,model:value('build-model'),label:value('build-label'),dry_run:checked('build-dry'),force:checked('build-force')});const lint=result.lint;const findings=[...(lint.hard_fails||[]),...(lint.flags||[])].map(item=>`<li><b>${esc(item.check)}</b>: ${esc(item.message)} ${esc((item.items||[]).join(' · '))}</li>`).join('');document.getElementById('build-result').innerHTML=`${result.blocked?banner('bad','Dispatch blocked by blinding lint.'):banner('ok',result.dry_run?'Dry run passed; nothing was published.':'Package published and output folder prepared.')}<p><b>Package:</b> <code>${esc(result.package_dir)}</code></p>${result.package_zip?`<p><b>Deliver this zip:</b> <code>${esc(result.package_zip)}</code> <span class="mut">— run the validator on it outside the project, then import its output below.</span></p>`:''}<p><b>Output:</b> <code>${esc(result.output_folder)}</code></p>${findings?`<ul>${findings}</ul>`:''}<details><summary>Provenance preview</summary><pre>${esc(JSON.stringify(result.provenance,null,2))}</pre></details>`;toast(result.dry_run?'Dry run passed':'Package built');if(result.published)DATA=await api('/api/bootstrap')}).catch(error=>{toast(error.message,true);document.getElementById('build-result').innerHTML=banner('bad',error.message)});
  document.getElementById('import-run').onclick=event=>busy(event.currentTarget,'Importing…',async()=>{const result=await post('/api/import',{stage:value('import-stage'),model:value('import-model'),source:value('import-source')});document.getElementById('import-result').innerHTML=banner('ok',`Imported ${result.count} files into ${result.run}`);toast('Outputs imported');DATA=await api('/api/bootstrap')}).catch(error=>{toast(error.message,true);document.getElementById('import-result').innerHTML=banner('bad',error.message)});
}

function renderPrompts(){app.innerHTML=`<div class="card hero"><div><div class="eyebrow">Model-facing turns</div><h2>Prompt renderer</h2><p>Cartridge placeholders and optional modules are resolved here. Operator reminders remain visually separated from paste-ready turns.</p></div></div><div class="card"><div class="row"><div class="field"><label>Stage</label><select id="prompt-stage">${stageOptions()}</select></div><div class="field"><label>Model</label><select id="prompt-model"></select></div><div class="field"><label>Method discussion mode</label><select id="prompt-mode"><option value="discuss">With discussion</option><option value="nodiscuss">Operator-reviewed lock</option></select></div></div><div class="actions"><button class="btn primary" id="prompt-render">Render prompt</button></div><div id="prompt-result"></div></div>`;
  const stage=document.getElementById('prompt-stage');const sync=()=>updateModels(stage.value,'prompt-model');stage.onchange=sync;sync();document.getElementById('prompt-render').onclick=event=>busy(event.currentTarget,'Rendering…',async()=>{const result=await api('/api/prompt',{stage:stage.value,model:value('prompt-model')||'PreviewModel',mode:value('prompt-mode')});document.getElementById('prompt-result').innerHTML=`<p class="mut">Source: <code>${esc(result.source)}</code> · Output: <code>${esc(result.output_folder)}</code> · Report: <code>${esc(result.report_name)}</code></p>${result.turns.map((turn,index)=>`<details class="turn" ${index===0?'open':''}><summary>Turn ${index+1} — ${esc(turn.title)}</summary><pre>${esc(turn.text)}</pre></details>`).join('')}${result.reminders?`<details class="turn"><summary>Operator reminders — do not paste</summary><pre>${esc(result.reminders)}</pre></details>`:''}`}).catch(error=>{toast(error.message,true);document.getElementById('prompt-result').innerHTML=banner('bad',error.message)});
}

function renderRuns(){const rows=DATA.runs.map(run=>`<tr class="clickable" data-run="${esc(run.path)}"><td>${stageChip(run.stage)}</td><td>${esc(run.model)}</td><td>${pill(run.returned,run.returned?'returned':'empty')}</td><td>${pill(run.graded,run.graded?'graded':'pending')}</td><td>${run.file_count}</td></tr>`).join('');app.innerHTML=`<div class="card hero"><div><div class="eyebrow">Operator-side outputs</div><h2>Runs</h2><p>Browse validator outputs only. The results key and private/operator-only directories are excluded from this view.</p></div><button class="btn" id="runs-refresh">Refresh</button></div><div class="card">${rows?`<table><thead><tr><th>Stage</th><th>Model/run</th><th>Returned</th><th>Graded</th><th>Files</th></tr></thead><tbody>${rows}</tbody></table>`:'<div class="empty">No validator run folders found.</div>'}</div><div id="run-detail"></div>`;
  document.querySelectorAll('[data-run]').forEach(row=>row.onclick=()=>loadRun(row.dataset.run));document.getElementById('runs-refresh').onclick=async()=>{DATA=await api('/api/bootstrap');renderRuns()};
}
async function loadRun(run){selectedRun=run;const detail=await api('/api/run',{run});const buttons=detail.files.map(file=>`<button data-file="${esc(file.path)}">${esc(file.path)} <span class="mut">${Math.ceil(file.size/1024)} KB</span></button>`).join('');document.getElementById('run-detail').innerHTML=`<div class="card"><h2>${esc(detail.name)}</h2><p class="mut">${stageChip(detail.stage)} · ${detail.file_count} files</p><div class="split"><div class="file-list">${buttons||'<div class="empty">Empty run folder</div>'}</div><div id="file-preview" class="empty">Select a file to preview.</div></div></div>`;document.querySelectorAll('[data-file]').forEach(button=>button.onclick=async()=>{document.querySelectorAll('[data-file]').forEach(item=>item.classList.remove('active'));button.classList.add('active');const result=await api('/api/file',{run,file:button.dataset.file});const target=document.getElementById('file-preview');if(result.kind==='image')target.innerHTML=`<img src="${result.data_url}" alt="${esc(button.dataset.file)}">`;else if(result.kind==='text')target.innerHTML=`<pre>${esc(result.text)}</pre>`;else target.innerHTML=`<div class="empty">${esc(result.message)}</div>`})}

function renderCompare(){const returned=DATA.runs.filter(run=>run.returned);const runOptions=returned.map(run=>`<option value="${esc(run.path)}">${esc(run.stage)} · ${esc(run.model)}</option>`).join('');app.innerHTML=`<div class="card hero"><div><div class="eyebrow">Question-level visual review</div><h2>Compare</h2><p>View validator and held-back original figures side by side. Notes remain operator-only and flow into review context.</p></div></div><div class="card"><div class="field"><label>Returned run</label><select id="compare-run">${runOptions||'<option value="">No returned runs</option>'}</select></div><div class="qnav" id="compare-qnav">${DATA.questions.map(question=>`<button data-q="${question.new}" title="${esc(question.topic)}">${question.new}</button>`).join('')}</div><div id="compare-result"></div></div>`;document.querySelectorAll('[data-q]').forEach(button=>button.onclick=()=>loadCompare(Number(button.dataset.q)));document.getElementById('compare-run').onchange=()=>loadCompare(selectedQuestion);if(returned.length)loadCompare(DATA.questions[0]?.new||1)}
async function loadCompare(question){selectedQuestion=question;document.querySelectorAll('[data-q]').forEach(button=>button.classList.toggle('active',Number(button.dataset.q)===question));const run=value('compare-run');if(!run)return;const result=await api('/api/compare',{run,question});const figures=items=>items.map(item=>`<figure><img src="${item.data_url}" alt="${esc(item.name)}"><figcaption class="mut">${esc(item.name)}</figcaption></figure>`).join('')||'<div class="empty">No matching figure.</div>';document.getElementById('compare-result').innerHTML=`<h3>Q${result.question.new} — ${esc(result.question.topic)}</h3><div class="fig-grid"><section><h3>Validator</h3>${figures(result.validator)}</section><section><h3>Original key</h3>${figures(result.original)}</section></div><label>Operator note</label><textarea id="compare-note">${esc(result.note||'')}</textarea><div class="actions"><button class="btn primary" id="compare-save">Save note</button></div>`;document.getElementById('compare-save').onclick=async()=>{await post('/api/note',{run,question,text:value('compare-note')});toast('Comparison note saved')}}

function ocell(ok){return ok?'<span class="pill ok">✓</span>':'<span class="pill bad">—</span>'}
async function renderOrigin(){
  loading('Loading origin…');
  let data;
  try{data=await api('/api/origin')}catch(error){app.innerHTML=`<div class="card hero"><div><div class="eyebrow">Held-back source of truth</div><h2>Origin report</h2></div></div><div class="card">${banner('bad',error.message)}</div>`;return}
  const counts=data.counts;
  const allGood=counts.total>0&&counts.ok===counts.total;
  const summary=counts.total===0?banner('warn','No question map found — add questions_map.yaml to verify separation.'):(allGood?banner('ok',`All ${counts.total} questions are functionally separated across the question, protocol, and origin-key documents — each can be scored on its own.`):banner('bad',`${counts.total-counts.ok} of ${counts.total} questions are missing an isolated section in at least one document. Resolve these before grading.`));
  const rows=data.rows.map(row=>`<tr class="clickable" data-orq="${row.new}"><td>${row.new}${row.original!==row.new?`<span class="mut"> · orig ${row.original}</span>`:''}</td><td>${esc(row.topic)}</td><td>${ocell(row.has_question)}</td><td>${ocell(row.has_protocol)}</td><td>${ocell(row.has_origin)}</td><td>${row.ok?pill(true,'scoreable'):'<span class="pill bad">gap</span>'}</td></tr>`).join('');
  app.innerHTML=`<div class="card hero"><div><div class="eyebrow">Held-back source of truth</div><h2>Origin report</h2><p>The origin report is withheld from every package. Confirm each question is split into its own section so the scorecard can grade it independently, read the report, and draft the result-free methodology sent to replication.</p></div><div class="pill">${esc(data.results_key)}</div></div>${summary}<div class="card"><h2>Per-question separation</h2><table><thead><tr><th>Q</th><th>Topic</th><th>Question</th><th>Protocol</th><th>Origin key</th><th>Status</th></tr></thead><tbody>${rows||'<tr><td colspan="6"><div class="empty">No questions configured.</div></td></tr>'}</tbody></table><p class="mut">Question = <code>${esc(data.questions_file.name||'QUESTIONS.md')}</code>, Protocol = <code>${esc(data.protocol.name||'ANALYSIS_PROTOCOL_OG.md')}</code>, Origin key = <code>${esc(data.summary.name||'(none)')}</code>. Origin sections are matched exactly as the scorecard extracts them (## Q&lt;original&gt;).</p><div id="origin-detail" class="empty">Select a question to preview its three sections.</div></div><div class="card"><h2>Origin report — ${esc(data.report.name||'not found')}</h2><div id="origin-report"><div class="empty">Loading report…</div></div></div><div class="card"><h2>Draft the methodology document</h2><p class="mut">Render a result-free prompt to send to the origin model (or your origin-author stand-in). Paste the returned protocol to write <code>${esc(data.protocol.path||'shared/ANALYSIS_PROTOCOL_OG.md')}</code> — the methods doc revealed only in replication.</p><div class="actions"><button class="btn" id="origin-gen">Render generation prompt</button></div><div id="origin-prompt"></div><label>Returned protocol (paste here)</label><textarea id="origin-protocol" placeholder="Paste the result-free protocol returned by the origin model…"></textarea><div class="actions"><button class="btn primary" id="origin-save">Save as protocol</button></div><div id="origin-save-result"></div></div><div class="card"><h2>Normalize the origin report (intake)</h2><p class="mut">Render an intake prompt for the origin model: it transcribes the report into the canonical per-question <code>${esc(data.summary.name||'SUMMARY.md')}</code> (stats keyed to the validator schema) plus a figure map. Transcribe-only — it never recomputes. The result fills the Origin-key column above and the Review stats table.</p><div class="actions"><button class="btn" id="intake-gen">Render intake prompt</button></div><div id="intake-prompt"></div><label>Returned intake (paste here)</label><textarea id="intake-text" placeholder="Paste the SUMMARY + figure_map returned by the origin model…"></textarea><div class="actions"><button class="btn primary" id="intake-save">Save SUMMARY + figures</button></div><div id="intake-save-result"></div></div>`;
  const detail=document.getElementById('origin-detail');
  document.querySelectorAll('[data-orq]').forEach(tr=>tr.onclick=()=>{
    document.querySelectorAll('[data-orq]').forEach(item=>item.classList.remove('active'));tr.classList.add('active');
    const row=data.rows.find(item=>item.new===Number(tr.dataset.orq));
    const block=(title,ok,text)=>`<section><h3>${esc(title)} ${ok?'<span class="pill ok">✓</span>':'<span class="pill bad">missing</span>'}</h3>${text&&text.trim()?`<pre>${esc(text)}</pre>`:'<div class="empty">No isolated section for this question.</div>'}</section>`;
    detail.className='';
    detail.innerHTML=`<h3>Q${row.new} — ${esc(row.topic)}</h3>${block('Question · '+(data.questions_file.name||'QUESTIONS.md'),row.has_question,row.question)}${block('Protocol · '+(data.protocol.name||'ANALYSIS_PROTOCOL_OG.md'),row.has_protocol,row.protocol)}${block('Origin key · '+(data.summary.name||'none'),row.has_origin,row.origin)}`;
  });
  loadOriginReport();
  document.getElementById('origin-gen').onclick=event=>busy(event.currentTarget,'Rendering…',async()=>{
    const result=await api('/api/origin/methodology_prompt');
    document.getElementById('origin-prompt').innerHTML=`<p class="mut">Source: <code>${esc(result.source)}</code> · writes to <code>${esc(result.target)}</code></p><textarea id="origin-prompt-text" readonly>${esc(result.text)}</textarea><div class="actions"><button class="btn" id="origin-copy">Copy prompt</button></div>`;
    document.getElementById('origin-copy').onclick=()=>{navigator.clipboard&&navigator.clipboard.writeText(result.text);toast('Prompt copied')};
  }).catch(error=>toast(error.message,true));
  document.getElementById('origin-save').onclick=event=>busy(event.currentTarget,'Saving…',async()=>{
    const text=value('origin-protocol');
    if(!text.trim()){toast('Paste the returned protocol first',true);return}
    const result=await post('/api/origin/methodology',{text});
    const warn=result.warnings&&result.warnings.length?`<div class="banner warn">Saved, but ${result.warnings.length} line(s) look like results — review for leaks.</div><ul class="mut">${result.warnings.slice(0,8).map(item=>`<li>L${item.line} (${esc(item.reason)}): ${esc(item.text)}</li>`).join('')}</ul>`:banner('ok','No result-like content detected.');
    document.getElementById('origin-save-result').innerHTML=`${banner('ok','Wrote '+result.written)}${warn}`;
    toast('Protocol saved');renderOrigin();
  }).catch(error=>{toast(error.message,true);document.getElementById('origin-save-result').innerHTML=banner('bad',error.message)});
  document.getElementById('intake-gen').onclick=event=>busy(event.currentTarget,'Rendering…',async()=>{
    const result=await api('/api/origin/intake_prompt');
    document.getElementById('intake-prompt').innerHTML=`<p class="mut">Source: <code>${esc(result.source)}</code> · writes to <code>${esc(result.target)}</code></p><textarea id="intake-prompt-text" readonly>${esc(result.text)}</textarea><div class="actions"><button class="btn" id="intake-copy">Copy prompt</button></div>`;
    document.getElementById('intake-copy').onclick=()=>{navigator.clipboard&&navigator.clipboard.writeText(result.text);toast('Prompt copied')};
  }).catch(error=>toast(error.message,true));
  document.getElementById('intake-save').onclick=event=>busy(event.currentTarget,'Saving…',async()=>{
    const text=value('intake-text');
    if(!text.trim()){toast('Paste the returned intake first',true);return}
    const result=await post('/api/origin/intake',{text});
    const figs=(result.figures||[]).length?`<ul class="mut">${result.figures.map(item=>`<li>Q${item.question} → ${esc(item.canonical)}: ${esc(item.status)}</li>`).join('')}</ul>`:'';
    const warn=(result.warnings||[]).length?`<div class="banner warn">Saved, but ${result.warnings.length} question(s) are missing fields — review.</div><ul class="mut">${result.warnings.slice(0,12).map(item=>`<li>Q${item.question} (${esc(item.reason)}): ${esc(item.text)}</li>`).join('')}</ul>`:banner('ok','All questions carry the required fields.');
    document.getElementById('intake-save-result').innerHTML=`${banner('ok','Wrote '+result.summary_written+(result.figure_map_written?' + '+result.figure_map_written:''))}${figs}${warn}`;
    toast('SUMMARY saved');renderOrigin();
  }).catch(error=>{toast(error.message,true);document.getElementById('intake-save-result').innerHTML=banner('bad',error.message)});
}
async function loadOriginReport(){
  const target=document.getElementById('origin-report');if(!target)return;
  try{
    const report=await api('/api/origin/report');
    if(report.kind==='pdf')target.innerHTML=`<iframe class="pdf" src="/api/origin/report.pdf?token=${encodeURIComponent(TOKEN)}" title="Origin report"></iframe><p class="mut">If the preview stays blank, open <code>${esc(report.abs)}</code> directly.</p>`;
    else if(report.kind==='text')target.innerHTML=`<pre>${esc(report.text)}</pre>`;
    else if(report.kind==='toolarge')target.innerHTML=`<div class="empty">Report is ${Math.ceil(report.size/1048576)} MB — too large to preview inline. Open <code>${esc(report.abs)}</code> directly.</div>`;
    else target.innerHTML=`<div class="empty">No inline preview for ${esc(report.name)}. Open <code>${esc(report.abs)}</code> directly.</div>`;
  }catch(error){target.innerHTML=`<div class="empty">${esc(error.message)}</div>`}
}
function renderScorecards(){const runOptions=DATA.runs.map(run=>`<option value="${esc(run.path)}">${esc(run.stage)} · ${esc(run.model)}</option>`).join('');const cards=DATA.scorecards.map(card=>`<tr class="clickable" data-card="${esc(card.path)}"><td>${esc(card.name)}</td><td>${Math.ceil(card.size/1024)} KB</td></tr>`).join('');app.innerHTML=`<div class="card hero"><div><div class="eyebrow">Human grading only</div><h2>Scorecards</h2><p>Generate a provisional side-by-side scaffold. The engine never assigns final verdicts.</p></div></div><div class="card"><div class="row"><div class="field"><label>Run</label><select id="score-run">${runOptions||'<option value="">No runs</option>'}</select></div><div class="field"><label>Stage</label><select id="score-stage">${stageOptions()}</select></div><div class="field"><label>Model label</label><input id="score-model" type="text"></div><div class="field"><label>License</label><input id="score-license" type="text" value="record-at-run-time"></div></div><div class="actions"><button class="btn primary" id="score-generate">Generate scaffold</button></div><div id="score-generate-result"></div></div><div class="card"><h2>Existing scorecards</h2>${cards?`<table><tbody>${cards}</tbody></table>`:'<div class="empty">No scorecards yet.</div>'}</div><div id="score-preview"></div>`;
  const runSelect=document.getElementById('score-run');const sync=()=>{const run=DATA.runs.find(item=>item.path===runSelect.value);if(run){document.getElementById('score-stage').value=run.stage;document.getElementById('score-model').value=run.model}};runSelect.onchange=sync;sync();document.getElementById('score-generate').onclick=event=>busy(event.currentTarget,'Generating…',async()=>{const result=await post('/api/scorecard',{run:value('score-run'),stage:value('score-stage'),model:value('score-model'),license:value('score-license')});document.getElementById('score-generate-result').innerHTML=banner('ok',`Created ${result.path}; all ${result.questions} verdicts remain provisional.`);DATA=await api('/api/bootstrap');toast('Scorecard scaffold generated')}).catch(error=>{toast(error.message,true);document.getElementById('score-generate-result').innerHTML=banner('bad',error.message)});document.querySelectorAll('[data-card]').forEach(row=>row.onclick=async()=>{const result=await api('/api/scorecard',{path:row.dataset.card});document.getElementById('score-preview').innerHTML=`<div class="card"><h2>${esc(result.path)}</h2><pre>${esc(result.text)}</pre></div>`})}

let REVIEW=null;
function renderReview(){
  const returned=DATA.runs.filter(run=>run.returned);
  const runOptions=returned.map(run=>`<option value="${esc(run.path)}">${esc(run.stage)} · ${esc(run.model)}${run.graded?' ✓':''}</option>`).join('');
  const cards=(DATA.scorecards||[]).map(card=>`<tr><td>${esc(card.name)}</td><td>${Math.ceil(card.size/1024)} KB</td><td>${card.protected?pill(true,'finalized'):'<span class="pill">draft</span>'}</td><td><button class="btn" data-card-view="${esc(card.path)}">View</button> <button class="btn danger" data-card-del="${esc(card.path)}"${card.protected?' disabled title="Reopen the run to delete"':''}>Delete</button></td></tr>`).join('');
  app.innerHTML=`<div class="card hero"><div><div class="eyebrow">Compare → grade → scorecard</div><h2>Review &amp; Grade</h2><p>Put the held-back original beside the validator answer for each question, confirm a verdict, then finalize to a scorecard. A run counts as graded only once every question is confirmed by you.</p></div></div>${returned.length?`<div class="card"><details class="turn"><summary>Overview — all runs (stats snapshot)</summary><div class="turn-body" id="overview-body"><div class="empty">Loading…</div></div></details></div>`:''}<div class="card"><div class="field"><label>Returned run</label><select id="review-run">${runOptions||'<option value="">No returned runs</option>'}</select></div><div id="review-body">${returned.length?'<div class="empty">Loading…</div>':'<div class="empty">No returned validator runs yet. Build and dispatch a package, then import the returned output folder.</div>'}</div></div><div class="card"><h2>Scorecards</h2>${cards?`<table><thead><tr><th>Scorecard</th><th>Size</th><th>State</th><th></th></tr></thead><tbody>${cards}</tbody></table>`:'<div class="empty">No scorecards yet. Finalize a fully-graded run to create one.</div>'}<div id="review-card-preview"></div></div>`;
  document.querySelectorAll('[data-card-view]').forEach(button=>button.onclick=async()=>{const result=await api('/api/scorecard',{path:button.dataset.cardView});document.getElementById('review-card-preview').innerHTML=`<div class="card"><h2>${esc(result.path)}</h2><div class="md">${md(result.text)}</div></div>`});
  document.querySelectorAll('[data-card-del]').forEach(button=>button.onclick=event=>busy(event.currentTarget,'Deleting…',async()=>{await post('/api/scorecard/delete',{path:button.dataset.cardDel});toast('Scorecard archived (restore from Files ▸ Archive)');DATA=await api('/api/bootstrap');renderReview()}).catch(error=>toast(error.message,true)));
  const runSelect=document.getElementById('review-run');
  if(returned.length){runSelect.onchange=()=>loadReviewRun(runSelect.value);loadReviewRun(returned.some(run=>run.path===selectedRun)?selectedRun:returned[0].path);loadOverview()}
}
async function loadOverview(){
  const target=document.getElementById('overview-body');if(!target)return;
  let data;try{data=await api('/api/overview')}catch(error){target.innerHTML=banner('bad',error.message);return}
  if(!data.runs.length){target.innerHTML='<div class="empty">No returned runs.</div>';return}
  const head=`<tr><th>Q</th><th>Topic</th><th class="v-origin">Origin</th>${data.runs.map(run=>`<th class="v-stage-${stageIndex(run.stage)}">${esc(run.model)}<div class="mut">${esc(run.stage)}</div></th>`).join('')}<th>Agree</th></tr>`;
  const body=data.rows.map(row=>{
    const cells=row.cells.map(cell=>{
      if(!cell.has_stats)return`<td class="mtx-cell mut clickable" data-run="${esc(cell.run)}" data-q="${row.new}" title="No Q${row.new}_summary.json — open to compare narratives">—</td>`;
      const dot=cell.in_origin?'ok':'no';
      const tip=cell.in_origin?`Matches origin (${esc(cell.origin_value)})`:'Not found in origin';
      const key=cell.label?esc(cell.label.split('.').pop())+'=':'';
      return`<td class="mtx-cell clickable" data-run="${esc(cell.run)}" data-q="${row.new}" title="${tip}"><span class="dot ${dot}"></span><code>${key}${esc(cell.value||'—')}</code></td>`;
    }).join('');
    return`<tr><td>${row.new}</td><td class="mut">${esc(row.topic)}</td><td class="v-origin"><code>${esc(row.origin_value||'—')}</code></td>${cells}<td class="mut">${esc(row.agreement)}</td></tr>`;
  }).join('');
  target.innerHTML=`<p class="mut">Headline statistic per run (top-level p-value where present). <span class="dot ok"></span> found in origin · <span class="dot no"></span> not in origin. Click any cell to open that question side-by-side below.</p><div class="mtx-scroll"><table class="mtx">${head}${body}</table></div>`;
  target.querySelectorAll('.mtx-cell.clickable').forEach(td=>td.onclick=()=>{selectedQuestion=Number(td.dataset.q);loadReviewRun(td.dataset.run);const body=document.getElementById('review-body');if(body)body.scrollIntoView({behavior:'smooth',block:'start'})});
}
async function loadReviewRun(run){
  selectedRun=run;document.getElementById('review-run').value=run;
  REVIEW=await api('/api/grading',{run});
  const done=REVIEW.verdicts.filter(item=>item.confirmed).length;
  const status=REVIEW.graded?banner('ok',`All ${REVIEW.total} questions confirmed.${REVIEW.finalized?' Finalized scorecard: '+esc(REVIEW.scorecard):' Ready to finalize.'}`):banner('warn',`${done} / ${REVIEW.total} questions confirmed — grading is incomplete.`);
  const qnav=REVIEW.verdicts.map(item=>`<button data-rq="${item.new}" class="${item.confirmed?'done':''}" title="${esc(item.topic)}">${item.new}</button>`).join('');
  const actions=`<div class="actions">${REVIEW.finalized?'<button class="btn" id="review-reopen">Reopen for editing</button>':`<button class="btn primary" id="review-finalize"${REVIEW.graded?'':' disabled'}>Finalize → scorecard</button>`}<button class="btn danger" id="review-del-grading"${REVIEW.finalized?' disabled title="Reopen first"':''}>Discard grading</button></div>`;
  document.getElementById('review-body').innerHTML=`${status}<div class="qnav" id="review-qnav">${qnav}</div><div id="review-q"></div>${actions}`;
  document.querySelectorAll('[data-rq]').forEach(button=>button.onclick=()=>loadReviewQuestion(Number(button.dataset.rq)));
  const finalize=document.getElementById('review-finalize');if(finalize)finalize.onclick=event=>busy(event.currentTarget,'Finalizing…',async()=>{await post('/api/grading/finalize',{run});toast('Scorecard created');DATA=await api('/api/bootstrap');renderReview()}).catch(error=>toast(error.message,true));
  const reopen=document.getElementById('review-reopen');if(reopen)reopen.onclick=event=>busy(event.currentTarget,'Reopening…',async()=>{await post('/api/grading/reopen',{run});toast('Reopened for editing');DATA=await api('/api/bootstrap');loadReviewRun(run)}).catch(error=>toast(error.message,true));
  const discard=document.getElementById('review-del-grading');if(discard)discard.onclick=event=>busy(event.currentTarget,'Discarding…',async()=>{await post('/api/grading/delete',{run});toast('Grading archived (restore from Files ▸ Archive)');DATA=await api('/api/bootstrap');loadReviewRun(run)}).catch(error=>toast(error.message,true));
  loadReviewQuestion(REVIEW.verdicts.some(item=>item.new===selectedQuestion)?selectedQuestion:(REVIEW.verdicts[0]?REVIEW.verdicts[0].new:1));
}
async function loadReviewQuestion(question){
  selectedQuestion=question;
  document.querySelectorAll('[data-rq]').forEach(button=>button.classList.toggle('active',Number(button.dataset.rq)===question));
  const run=selectedRun;const result=await api('/api/compare',{run,question});
  const originClass='v-origin';
  const valClass='v-stage-'+stageIndex(result.run&&result.run.stage);
  const figures=items=>(items||[]).map(item=>`<figure id="fig-${figStem(item.name)}"><img src="${item.data_url}" alt="${esc(item.name)}"><figcaption class="mut">${esc(item.name)}</figcaption></figure>`).join('')||'<div class="empty">No figures.</div>';
  const legend=(result.legend||[]).map(verdict=>`<option value="${esc(verdict)}"${result.verdict===verdict?' selected':''}>${esc(verdict)}</option>`).join('');
  const stageNote=result.expect_exact?banner('warn','Replication stage — the validator should reproduce the origin’s statistics, so treat any “— not reported” as a discrepancy to check.'):banner('ok','Robustness stage — the validator chose its own method, so different or missing statistics can be legitimate. Lean on the narratives.');
  const originCell=stat=>stat.in_origin?`<code class="${originClass}">${esc(stat.origin_value)}</code>${stat.origin_context?`<div class="mut ctx">${esc(stat.origin_context)}</div>`:''}`:'<span class="mut">— not reported</span>';
  const statRows=(result.stats||[]).map(stat=>`<tr><td>${esc(stat.label)}</td><td><code class="${valClass}">${esc(stat.value)}</code></td><td>${originCell(stat)}</td></tr>`).join('');
  const statsCaption='<p class="mut">The origin value is the validator’s number located in the origin’s text for this question (in the origin’s own representation — e.g. a percentage), with the surrounding snippet. “— not reported” means that exact number isn’t in the origin.</p>';
  const statsBody=result.has_validator_stats?`${statsCaption}<table><thead><tr><th>Statistic</th><th class="${valClass}">Validator value</th><th class="${originClass}">Origin value</th></tr></thead><tbody>${statRows}</tbody></table>`:`<div class="empty">No machine-readable Q${result.question.new}_summary.json from this validator — compare via the narratives below.</div>`;
  const onlyRows=(result.origin_only||[]).map(item=>`<tr><td><code class="${originClass}">${esc(item.value)}</code></td><td class="mut">${esc(item.context)}</td></tr>`).join('');
  const onlyBody=onlyRows?`<p class="mut">Numbers in the origin’s material for this question that don’t match any value the validator reported — the origin may have measured more.</p><table><thead><tr><th>Origin value</th><th>Context</th></tr></thead><tbody>${onlyRows}</tbody></table>`:'<div class="empty">None — every origin figure for this question matched a validator value.</div>';
  const narrative=(title,source,text,cls,marks)=>`<section><h4 class="${cls}">${esc(title)}${source?` <span class="mut">· ${esc(source)}</span>`:''}</h4>${text&&text.trim()?`<div class="md">${highlightStats(md(text),marks,cls)}</div>`:'<div class="empty">No report section for this question.</div>'}</section>`;
  const figSection=(label,cls,items)=>`<section><h4 class="${cls}">${esc(label)}</h4><div class="figs">${figures(items)}</div></section>`;
  const sec=(title,body)=>`<details class="turn" open><summary>${title}</summary><div class="turn-body">${body}</div></details>`;
  const onlyCount=result.origin_only&&result.origin_only.length?` (${result.origin_only.length})`:'';
  document.getElementById('review-q').innerHTML=`<h3>Q${result.question.new} — ${esc(result.question.topic)} ${result.confirmed?'<span class="pill ok">confirmed</span>':'<span class="pill">unconfirmed</span>'}</h3>${stageNote}${sec('Reported statistics — origin vs validator',statsBody)}${sec('Origin-only figures'+onlyCount,onlyBody)}${sec('Full reports',`<div class="grade-cols two">${narrative('Origin',result.origin_narrative_source,result.origin_narrative,originClass,result.origin_highlights)}${narrative('Validator',result.validator_narrative_source,result.validator_narrative,valClass,result.validator_highlights)}</div>`)}${sec('Figures',`<div class="grade-cols two">${figSection('Origin',originClass,result.original)}${figSection('Validator',valClass,result.validator)}</div>`)}${sec('Verdict',`<div class="field"><label>Verdict</label><select id="review-verdict"><option value="">— select —</option>${legend}</select></div><label>Grader note</label><textarea id="review-note">${esc(result.note||'')}</textarea><div class="actions"><button class="btn primary" id="review-confirm">Confirm verdict</button><button class="btn" id="review-clear">Clear</button></div>`)}`;
  document.querySelectorAll('#review-q [data-fig]').forEach(link=>link.onclick=()=>{const target=document.getElementById('fig-'+link.dataset.fig);if(target){target.scrollIntoView({behavior:'smooth',block:'center'});target.classList.add('flash');setTimeout(()=>target.classList.remove('flash'),1300)}else{toast('No matching figure is shown for this question',true)}});
  document.getElementById('review-confirm').onclick=event=>busy(event.currentTarget,'Saving…',async()=>{const verdict=value('review-verdict');if(!verdict){toast('Pick a verdict first',true);return}await post('/api/grading/verdict',{run,question,verdict,note:value('review-note'),confirmed:true});toast('Verdict confirmed');loadReviewRun(run)}).catch(error=>toast(error.message,true));
  document.getElementById('review-clear').onclick=event=>busy(event.currentTarget,'Clearing…',async()=>{await post('/api/grading/verdict',{run,question,verdict:'',note:'',confirmed:false});toast('Verdict cleared');loadReviewRun(run)}).catch(error=>toast(error.message,true));
}

refresh().catch(error=>{app.innerHTML=`<div class="card">${banner('bad',error.message)}</div>`});
