"""Alias system for RRG dispatch validators.

Creates short shell aliases that map to `rrg dispatch --validator X` so you
can type `grok-val "prompt"` instead of `rrg dispatch --validator grok --stage ...`.

Aliases are stored in .rrg_prefs.yaml under the `aliases` key:
    aliases:
        grok-val: {validator: grok}
        codex-val: {validator: codex, model: gpt-5.6-terra}

Each alias generates a shell function that:
  - Calls `rrg dispatch` with the alias's validator and model
  - Passes through all extra arguments (like --continue, --resume, --stage)
  - Can be sourced from ~/.rrg_aliases.sh
"""

from __future__ import annotations

import os
import shlex
from pathlib import Path
from typing import Any

from .prefs import load_prefs, save_prefs
from .project import Project

SHELL_HEADER = """\
# RRG dispatch aliases — generated by `rrg alias`
# Source this file in your shell rc:
#   source ~/.rrg_aliases.sh
"""

SHELL_FOOTER = """\
# End of RRG aliases
"""


def _normalize_alias_name(name: str) -> str:
    """Normalize an alias name to a valid shell function name."""
    import re
    name = re.sub(r"[^A-Za-z0-9_-]", "-", name)
    name = name.strip("-")
    return name or "rrg-alias"


def list_aliases(project: Project) -> dict[str, dict[str, str]]:
    """Return all configured aliases."""
    prefs = load_prefs(project)
    return prefs.get("aliases", {}) or {}


def set_alias(project: Project, name: str, validator: str, model: str | None = None) -> dict[str, Any]:
    """Create or update an alias."""
    name = _normalize_alias_name(name)
    prefs = load_prefs(project)
    aliases = prefs.get("aliases", {}) or {}
    alias_entry = {"validator": validator}
    if model:
        alias_entry["model"] = model
    aliases[name] = alias_entry
    save_prefs(project, {"aliases": aliases})
    return {"name": name, "validator": validator, "model": model or "(default)"}


def remove_alias(project: Project, name: str) -> dict[str, Any]:
    """Remove an alias."""
    prefs = load_prefs(project)
    aliases = prefs.get("aliases", {}) or {}
    if name not in aliases:
        return {"removed": False, "name": name, "reason": "not found"}
    del aliases[name]
    save_prefs(project, {"aliases": aliases})
    return {"removed": True, "name": name}


def generate_shell_function(name: str, validator: str, model: str | None = None) -> str:
    """Generate a shell function for an alias."""
    name = _normalize_alias_name(name)
    # Build the base command
    parts = ["rrg", "dispatch", "--validator", shlex.quote(validator)]
    if model:
        parts.extend(["--model", shlex.quote(model)])
    base_cmd = " ".join(parts)

    # The function passes through all args, but extracts --continue/--resume
    # to use as the session continuation mechanism.
    return f"""\
{name}() {{
    # Alias: {name} → rrg dispatch --validator {validator}{f" --model {model}" if model else ""}
    # Usage: {name} --stage S --model M [other rrg dispatch flags]
    #   {name} --stage replication --model "Qwen"  # first call
    #   {name} --stage replication --model "Qwen" --reuse  # reuse package
    {base_cmd} "$@"
}}"""


def generate_shell_file(project: Project) -> str:
    """Generate the full shell file with all aliases."""
    aliases = list_aliases(project)
    lines = [SHELL_HEADER]
    for name, entry in sorted(aliases.items()):
        validator = entry.get("validator", "manual")
        model = entry.get("model")
        lines.append(generate_shell_function(name, validator, model))
        lines.append("")
    lines.append(SHELL_FOOTER)
    return "\n".join(lines)


def install_aliases(project: Project) -> dict[str, Any]:
    """Write the shell file to ~/.rrg_aliases.sh and print install instructions."""
    shell_file = Path.home() / ".rrg_aliases.sh"
    content = generate_shell_file(project)
    shell_file.write_text(content, encoding="utf-8")

    # Check if the shell rc already sources it
    rc_files = [Path.home() / ".zshrc", Path.home() / ".bashrc"]
    source_line = 'source ~/.rrg_aliases.sh'
    already_sourced = False
    for rc in rc_files:
        if rc.exists():
            if source_line in rc.read_text(encoding="utf-8", errors="ignore"):
                already_sourced = True
                break

    aliases = list_aliases(project)
    return {
        "installed": True,
        "path": str(shell_file),
        "aliases": list(aliases.keys()),
        "already_sourced": already_sourced,
        "instructions": (
            f"Shell file written to {shell_file}. Add this line to your shell rc:\n"
            f"  source ~/.rrg_aliases.sh"
        ) if not already_sourced else f"Already sourced in your shell rc.",
    }
